//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DowJones.Web.Mvc.UI.Components.HeadlineListCarousel
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 02/08/2012 03:21 PM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.HeadlineListCarousel.HeadlineListCarousel.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.HeadlineListCarousel.HeadlineListCarouselControl))]
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.HeadlineListCarousel.jquery.jcarousel.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.HeadlineListCarousel.HeadlineListCarouselControl))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.HeadlineListCarousel.HeadlineListCarouselClientTem" +
        "plate.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="itemTemplate", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.HeadlineListCarousel.HeadlineListCarouselControl))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.29745")]
    public class HeadlineListCarouselControl : DowJones.Web.Mvc.UI.ViewComponentBase<HeadlineListCarouselModel>
    {
#line hidden

        public HeadlineListCarouselControl()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_headlineListCarousel";
            }
        }
        public override void ExecuteTemplate()
        {





WriteLiteral("\r\n<div class=\'headline-snippet-container-vertical-hover\'></div>\r\n\r\n<ul class=\"dj_" +
"carousel jcarousel-skin-");


                                 Write(Model.SkinName);

WriteLiteral("\">\r\n");


       var index = 0; 


     foreach(var headline in Model.Headlines) {

WriteLiteral("        <li class=\"jcarousel-item jcarousel-item-vertical jcarousel-item-");


                                                                    Write(index);

WriteLiteral(" jcarousel-item-");


                                                                                          Write(index);

WriteLiteral("-vertical\" jcarouselindex=\"");


                                                                                                                            Write(index++);

WriteLiteral("\" style=\"display:none\">\r\n            <div class=\"headline-container-vertical\">\r\n\r" +
"\n                ");



WriteLiteral("\r\n                <div class=\"headline-image-container-vertical\">\r\n              " +
"      <a href=\"");


                         Write(headline.ThumbnailHref);

WriteLiteral("\">\r\n                        <img class=\"image\" src=\"");


                                           Write(headline.ThumbnailSourceUri);

WriteLiteral("\" />\r\n                    </a>\r\n                </div>\r\n\r\n                ");



WriteLiteral("\r\n                <div class=\"headline-title-container-vertical\">\r\n              " +
"      <a class=\"link\" href=\"");


                                     Write(headline.ExternalUri);

WriteLiteral("\">\r\n                        ");



WriteLiteral("\r\n");


                         foreach(var item in headline.TitleItems){
WriteLiteral("<span>");


                                                                   Write(item);

WriteLiteral("</span>");



WriteLiteral("<span />");


                                                                                            }

WriteLiteral("                    </a>\r\n                </div>\r\n\r\n                ");



WriteLiteral("\r\n                <div class=\"headline-time-container-vertical\">\r\n               " +
"     <span class=\"time\">");


                                  Write(headline.Time);

WriteLiteral("</span>\r\n                </div>\r\n\r\n                ");



WriteLiteral("\r\n                <div class=\"headline-extension-container-vertical\" style=\"displ" +
"ay: none;\">\r\n                    <span class=\"extension\" />\r\n                </d" +
"iv>\r\n\r\n                ");



WriteLiteral("\r\n                <div class=\"headline-snippet-container-vertical-inline\" />\r\n\r\n " +
"           </div>\r\n        </li>\r\n");


    }

WriteLiteral("\r\n</ul>");


        }
    }
}
