var mockTweets = {
    "data": [{
        "coordinates": null,
        "created_at": "Wed Jul 06 08:27:52 +0000 2011",
        "truncated": false,
        "favorited": false,
        "id_str": 88524551671132160,
        "in_reply_to_user_id_str": null,
        "entities": {
            "urls": [{
                "expanded_url": "http://twitpic.com/5lyazm",
                "url": "http://t.co/YfENPIc",
                "indices": [51, 70],
                "display_url": "twitpic.com/5lyazm"
            }],
            "hashtags": [],
            "user_mentions": []
        },
        "contributors": null,
        "text": "This month's non-Kindle Reading List, as a stack:  http://t.co/YfENPIc",
        "id": 88524551671132160,
        "retweet_count": 0,
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "user": {
            "name": "Scott Hanselman",
            "profile_sidebar_border_color": "b8aa9c",
            "profile_background_tile": true,
            "profile_sidebar_fill_color": "b8aa9c",
            "created_at": "Tue May 01 05:55:26 +0000 2007",
            "location": "Portland, Oregon",
            "profile_image_url": "http://a2.twimg.com/profile_images/1425619283/image_normal.jpg",
            "is_translator": false,
            "profile_link_color": "72412c",
            "id_str": 5676102,
            "follow_request_sent": false,
            "url": "http://hanselman.com",
            "favourites_count": 2336,
            "contributors_enabled": false,
            "default_profile": false,
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1425619283/image_normal.jpg",
            "utc_offset": "-28800",
            "id": 5676102,
            "profile_use_background_image": true,
            "listed_count": 4063,
            "protected": false,
            "followers_count": 38825,
            "lang": "en",
            "profile_text_color": 696969,
            "geo_enabled": true,
            "profile_background_color": "d1cdc1",
            "time_zone": "Pacific Time (US & Canada)",
            "verified": false,
            "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "notifications": false,
            "description": "Tech, Diabetes, Parenting, Race, Linguistics, Fashion, Podcasting, Media, Culture, Code, Ratchet.",
            "default_profile_image": false,
            "friends_count": 2695,
            "profile_background_image_url": "http://a3.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "statuses_count": 44794,
            "following": true,
            "show_all_inline_media": true,
            "screen_name": "shanselman"
        },
        "place": null,
        "in_reply_to_screen_name": null,
        "source": "<a href=\"http://twitter.com/#!/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
        "in_reply_to_status_id": null
    },
    {
        "coordinates": null,
        "truncated": false,
        "created_at": "Wed Jul 06 08:05:28 +0000 2011",
        "favorited": false,
        "retweeted_status": {
            "coordinates": null,
            "truncated": false,
            "created_at": "Wed Jul 06 08:02:52 +0000 2011",
            "favorited": false,
            "id_str": 88518261217570820,
            "entities": {
                "urls": [],
                "hashtags": [],
                "user_mentions": []
            },
            "in_reply_to_user_id_str": null,
            "contributors": null,
            "text": "There is no problem animated GIFs cannot solve.",
            "id": 88518261217570820,
            "retweet_count": "100+",
            "in_reply_to_status_id_str": null,
            "geo": null,
            "retweeted": false,
            "in_reply_to_user_id": null,
            "source": "web",
            "in_reply_to_screen_name": null,
            "user": {
                "profile_sidebar_fill_color": "e0e1f5",
                "profile_sidebar_border_color": "e0e1f5",
                "name": "Jeff Atwood",
                "profile_background_tile": true,
                "location": "Bay Area, CA",
                "profile_image_url": "http://a1.twimg.com/profile_images/58911850/coding-horror-gravatar-128_normal.png",
                "created_at": "Sun Apr 29 20:50:37 +0000 2007",
                "is_translator": false,
                "profile_link_color": "282d58",
                "id_str": 5637652,
                "follow_request_sent": false,
                "default_profile": false,
                "favourites_count": 159,
                "url": "http://www.codinghorror.com/blog",
                "contributors_enabled": false,
                "id": 5637652,
                "utc_offset": "-25200",
                "profile_image_url_https": "https://si0.twimg.com/profile_images/58911850/coding-horror-gravatar-128_normal.png",
                "profile_use_background_image": true,
                "listed_count": 4767,
                "lang": "en",
                "profile_text_color": "383a48",
                "followers_count": 52371,
                "protected": false,
                "geo_enabled": false,
                "profile_background_color": "fff",
                "description": "Is it more interesting to talk about software than it is to develop software?",
                "time_zone": "Arizona",
                "verified": false,
                "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/623412/hunt-wumpus-bg.png",
                "notifications": false,
                "default_profile_image": false,
                "friends_count": 69,
                "profile_background_image_url": "http://a2.twimg.com/profile_background_images/623412/hunt-wumpus-bg.png",
                "statuses_count": 22225,
                "screen_name": "codinghorror",
                "show_all_inline_media": false,
                "following": false
            },
            "place": null,
            "in_reply_to_status_id": null
        },
        "id_str": 88518916447547400,
        "entities": {
            "urls": [],
            "hashtags": [],
            "user_mentions": [{
                "name": "Jeff Atwood",
                "id_str": 5637652,
                "id": 5637652,
                "indices": [3, 16],
                "screen_name": "codinghorror"
            }]
        },
        "in_reply_to_user_id_str": null,
        "contributors": null,
        "text": "RT @codinghorror: There is no problem animated GIFs cannot solve.",
        "id": 88518916447547400,
        "retweet_count": "100+",
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "source": "<a href=\"http://twitter.com/#!/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
        "in_reply_to_screen_name": null,
        "user": {
            "profile_sidebar_fill_color": "b8aa9c",
            "profile_sidebar_border_color": "b8aa9c",
            "name": "Scott Hanselman",
            "profile_background_tile": true,
            "location": "Portland, Oregon",
            "profile_image_url": "http://a2.twimg.com/profile_images/1425619283/image_normal.jpg",
            "created_at": "Tue May 01 05:55:26 +0000 2007",
            "is_translator": false,
            "profile_link_color": "72412c",
            "id_str": 5676102,
            "follow_request_sent": false,
            "default_profile": false,
            "favourites_count": 2336,
            "url": "http://hanselman.com",
            "contributors_enabled": false,
            "id": 5676102,
            "utc_offset": "-28800",
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1425619283/image_normal.jpg",
            "profile_use_background_image": true,
            "listed_count": 4063,
            "lang": "en",
            "profile_text_color": 696969,
            "followers_count": 38832,
            "protected": false,
            "geo_enabled": true,
            "profile_background_color": "d1cdc1",
            "description": "Tech, Diabetes, Parenting, Race, Linguistics, Fashion, Podcasting, Media, Culture, Code, Ratchet.",
            "time_zone": "Pacific Time (US & Canada)",
            "verified": false,
            "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "notifications": false,
            "default_profile_image": false,
            "friends_count": 2695,
            "profile_background_image_url": "http://a3.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "statuses_count": 44794,
            "screen_name": "shanselman",
            "show_all_inline_media": true,
            "following": true
        },
        "place": null,
        "in_reply_to_status_id": null
    },
    {
        "coordinates": null,
        "truncated": false,
        "created_at": "Wed Jul 06 07:58:21 +0000 2011",
        "favorited": false,
        "id_str": 88517125152571400,
        "entities": {
            "urls": [],
            "hashtags": [],
            "user_mentions": []
        },
        "in_reply_to_user_id_str": null,
        "contributors": null,
        "text": "\"Bad love letters beg for love back. Good love letters ask for nothing.\"",
        "id": 88517125152571400,
        "retweet_count": 13,
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "source": "<a href=\"http://twitter.com/#!/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
        "in_reply_to_screen_name": null,
        "user": {
            "profile_sidebar_fill_color": "b8aa9c",
            "profile_sidebar_border_color": "b8aa9c",
            "name": "Scott Hanselman",
            "profile_background_tile": true,
            "location": "Portland, Oregon",
            "profile_image_url": "http://a2.twimg.com/profile_images/1425619283/image_normal.jpg",
            "created_at": "Tue May 01 05:55:26 +0000 2007",
            "follow_request_sent": false,
            "is_translator": false,
            "profile_link_color": "72412c",
            "id_str": 5676102,
            "favourites_count": 2336,
            "default_profile": false,
            "contributors_enabled": false,
            "url": "http://hanselman.com",
            "id": 5676102,
            "utc_offset": "-28800",
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1425619283/image_normal.jpg",
            "profile_use_background_image": true,
            "listed_count": 4064,
            "lang": "en",
            "profile_text_color": 696969,
            "followers_count": 38832,
            "protected": false,
            "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "profile_background_color": "d1cdc1",
            "description": "Tech, Diabetes, Parenting, Race, Linguistics, Fashion, Podcasting, Media, Culture, Code, Ratchet.",
            "time_zone": "Pacific Time (US & Canada)",
            "verified": false,
            "geo_enabled": true,
            "notifications": false,
            "friends_count": 2695,
            "profile_background_image_url": "http://a3.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "default_profile_image": false,
            "statuses_count": 44794,
            "screen_name": "shanselman",
            "following": true,
            "show_all_inline_media": true
        },
        "place": null,
        "in_reply_to_status_id": null
    },
    {
        "coordinates": null,
        "truncated": false,
        "created_at": "Wed Jul 06 06:20:20 +0000 2011",
        "favorited": false,
        "retweeted_status": {
            "coordinates": null,
            "truncated": false,
            "created_at": "Wed Jul 06 06:16:39 +0000 2011",
            "favorited": false,
            "id_str": 88491531060789250,
            "entities": {
                "urls": [],
                "hashtags": [],
                "user_mentions": [{
                    "name": "dream hampton",
                    "id_str": 122208388,
                    "id": 122208388,
                    "indices": [0, 13],
                    "screen_name": "dreamhampton"
                }]
            },
            "in_reply_to_user_id_str": 122208388,
            "contributors": null,
            "text": "@dreamhampton lol! \"Twitter.. I wish I knew how to quit you.\"",
            "id": 88491531060789250,
            "retweet_count": 1,
            "in_reply_to_status_id_str": 88490986384269310,
            "geo": null,
            "retweeted": false,
            "in_reply_to_user_id": 122208388,
            "source": "<a href=\"http://ubersocial.com\" rel=\"nofollow\">UberSocial for BlackBerry</a>",
            "in_reply_to_screen_name": "dreamhampton",
            "user": {
                "profile_sidebar_fill_color": "DAECF4",
                "profile_sidebar_border_color": "C6E2EE",
                "name": "Machinko",
                "profile_background_tile": true,
                "location": "By the door.",
                "profile_image_url": "http://a0.twimg.com/profile_images/1380660916/Machinko_72dpi020_normal.JPG",
                "created_at": "Tue Oct 07 06:39:30 +0000 2008",
                "profile_link_color": "1F98C7",
                "id_str": 16626601,
                "follow_request_sent": false,
                "is_translator": false,
                "default_profile": false,
                "contributors_enabled": false,
                "favourites_count": 803,
                "url": "http://www.newmoneymachinko.tumblr.com",
                "id": 16626601,
                "profile_image_url_https": "https://si0.twimg.com/profile_images/1380660916/Machinko_72dpi020_normal.JPG",
                "utc_offset": "-18000",
                "profile_use_background_image": true,
                "listed_count": 236,
                "lang": "en",
                "profile_text_color": "663B12",
                "followers_count": 5050,
                "protected": false,
                "profile_background_color": "C6E2EE",
                "geo_enabled": false,
                "description": "If Aiyana Jones had been a little Jewish girl, the First 48 would no longer be on the air.",
                "time_zone": "Eastern Time (US & Canada)",
                "verified": false,
                "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/78135852/SoulCulturePic.jpg",
                "notifications": false,
                "friends_count": 889,
                "default_profile_image": false,
                "statuses_count": 138380,
                "profile_background_image_url": "http://a2.twimg.com/profile_background_images/78135852/SoulCulturePic.jpg",
                "screen_name": "MeLaMachinko",
                "show_all_inline_media": true,
                "following": false
            },
            "place": null,
            "in_reply_to_status_id": 88490986384269310
        },
        "id_str": 88492454889787400,
        "entities": {
            "urls": [],
            "hashtags": [],
            "user_mentions": [{
                "name": "Machinko",
                "id_str": 16626601,
                "id": 16626601,
                "indices": [3, 16],
                "screen_name": "MeLaMachinko"
            },
            {
                "name": "dream hampton",
                "id_str": 122208388,
                "id": 122208388,
                "indices": [18, 31],
                "screen_name": "dreamhampton"
            }]
        },
        "in_reply_to_user_id_str": null,
        "contributors": null,
        "text": "RT @MeLaMachinko: @dreamhampton lol! \"Twitter.. I wish I knew how to quit you.\"",
        "id": 88492454889787400,
        "retweet_count": 1,
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "source": "<a href=\"http://tweetlogix.com\" rel=\"nofollow\">Tweetlogix</a>",
        "in_reply_to_screen_name": null,
        "user": {
            "profile_sidebar_fill_color": "b8aa9c",
            "profile_sidebar_border_color": "b8aa9c",
            "name": "Scott Hanselman",
            "profile_background_tile": true,
            "location": "Portland, Oregon",
            "profile_image_url": "http://a2.twimg.com/profile_images/1425619283/image_normal.jpg",
            "created_at": "Tue May 01 05:55:26 +0000 2007",
            "profile_link_color": "72412c",
            "id_str": 5676102,
            "follow_request_sent": false,
            "is_translator": false,
            "default_profile": false,
            "contributors_enabled": false,
            "favourites_count": 2336,
            "url": "http://hanselman.com",
            "id": 5676102,
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1425619283/image_normal.jpg",
            "utc_offset": "-28800",
            "profile_use_background_image": true,
            "listed_count": 4063,
            "lang": "en",
            "profile_text_color": 696969,
            "followers_count": 38832,
            "protected": false,
            "profile_background_color": "d1cdc1",
            "geo_enabled": true,
            "description": "Tech, Diabetes, Parenting, Race, Linguistics, Fashion, Podcasting, Media, Culture, Code, Ratchet.",
            "time_zone": "Pacific Time (US & Canada)",
            "verified": false,
            "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "notifications": false,
            "friends_count": 2695,
            "default_profile_image": false,
            "statuses_count": 44794,
            "profile_background_image_url": "http://a3.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "screen_name": "shanselman",
            "show_all_inline_media": true,
            "following": true
        },
        "place": null,
        "in_reply_to_status_id": null
    },
    {
        "coordinates": null,
        "created_at": "Wed Jul 06 05:38:40 +0000 2011",
        "truncated": false,
        "favorited": false,
        "id_str": 88481971566673920,
        "in_reply_to_user_id_str": null,
        "entities": {
            "urls": [],
            "hashtags": [],
            "user_mentions": [{
                "name": "Idris Elba",
                "id_str": 92717138,
                "id": 92717138,
                "indices": [67, 77],
                "screen_name": "idriselba"
            }]
        },
        "contributors": null,
        "text": "Holy crap. \"Luther\" is on NetFlix Instant. HIGHLY RECOMMENDED. /cc @idriselba",
        "id": 88481971566673920,
        "retweet_count": 5,
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "user": {
            "name": "Scott Hanselman",
            "profile_sidebar_border_color": "b8aa9c",
            "profile_background_tile": true,
            "profile_sidebar_fill_color": "b8aa9c",
            "created_at": "Tue May 01 05:55:26 +0000 2007",
            "location": "Portland, Oregon",
            "profile_image_url": "http://a2.twimg.com/profile_images/1425619283/image_normal.jpg",
            "profile_link_color": "72412c",
            "id_str": 5676102,
            "follow_request_sent": null,
            "is_translator": false,
            "default_profile": false,
            "url": "http://hanselman.com",
            "favourites_count": 2336,
            "contributors_enabled": false,
            "utc_offset": "-28800",
            "id": 5676102,
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1425619283/image_normal.jpg",
            "profile_use_background_image": true,
            "listed_count": 4063,
            "protected": false,
            "followers_count": 38831,
            "lang": "en",
            "profile_text_color": 696969,
            "profile_background_color": "d1cdc1",
            "time_zone": "Pacific Time (US & Canada)",
            "verified": false,
            "geo_enabled": true,
            "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "notifications": null,
            "description": "Tech, Diabetes, Parenting, Race, Linguistics, Fashion, Podcasting, Media, Culture, Code, Ratchet.",
            "friends_count": 2695,
            "profile_background_image_url": "http://a3.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "default_profile_image": false,
            "statuses_count": 44794,
            "following": null,
            "screen_name": "shanselman",
            "show_all_inline_media": true
        },
        "place": null,
        "in_reply_to_screen_name": null,
        "source": "<a href=\"http://twitter.com/#!/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
        "in_reply_to_status_id": null
    },
    {
        "coordinates": null,
        "truncated": false,
        "created_at": "Wed Jul 06 05:22:45 +0000 2011",
        "favorited": false,
        "id_str": 88477963900825600,
        "entities": {
            "urls": [],
            "hashtags": [],
            "user_mentions": []
        },
        "in_reply_to_user_id_str": null,
        "contributors": null,
        "text": "In Mountain View ... visiting.",
        "id": 88477963900825600,
        "retweet_count": 0,
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "source": "<a href=\"http://twitter.com/#!/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
        "in_reply_to_screen_name": null,
        "user": {
            "profile_sidebar_fill_color": "F1F2E8",
            "profile_sidebar_border_color": "F1F2E8",
            "name": "Nikhil Kothari",
            "profile_background_tile": true,
            "location": "Sammamish, WA",
            "profile_image_url": "http://a3.twimg.com/profile_images/1290194669/TwitterProfile_normal.jpg",
            "created_at": "Wed Jan 09 09:48:21 +0000 2008",
            "follow_request_sent": false,
            "is_translator": false,
            "profile_link_color": "148FE4",
            "id_str": 12019742,
            "contributors_enabled": false,
            "favourites_count": 3018,
            "default_profile": false,
            "url": "http://www.nikhilk.net",
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1290194669/TwitterProfile_normal.jpg",
            "id": 12019742,
            "utc_offset": "-28800",
            "profile_use_background_image": true,
            "listed_count": 491,
            "lang": "en",
            "profile_text_color": "3E3E3E",
            "followers_count": 5204,
            "protected": false,
            "profile_background_color": "569FD2",
            "description": "Software architect at Microsoft (working on Bing mobile; worked on Silverlight, RIA Services and ASP.NET), Script# creator, photography enthusiast, ...",
            "time_zone": "Pacific Time (US & Canada)",
            "verified": false,
            "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/244067317/xe3b71c4c3e6b01802d4bf8e7eb850cb.png",
            "notifications": false,
            "geo_enabled": true,
            "statuses_count": 3569,
            "profile_background_image_url": "http://a3.twimg.com/profile_background_images/244067317/xe3b71c4c3e6b01802d4bf8e7eb850cb.png",
            "friends_count": 160,
            "default_profile_image": false,
            "screen_name": "nikhilk",
            "show_all_inline_media": false,
            "following": true
        },
        "place": null,
        "in_reply_to_status_id": null
    },
    {
        "coordinates": null,
        "truncated": false,
        "created_at": "Wed Jul 06 04:26:05 +0000 2011",
        "favorited": false,
        "id_str": 88463704835887100,
        "entities": {
            "urls": [],
            "hashtags": [],
            "user_mentions": [{
                "name": "Overheard At Home",
                "id_str": 19046820,
                "id": 19046820,
                "indices": [122, 138],
                "screen_name": "overheardathome"
            }]
        },
        "in_reply_to_user_id_str": null,
        "contributors": null,
        "text": "My 3yo: \"How do girls pee?\"\nMe: \"From their girl parts.\"\n*uncomfortable pause*\n3yo: \"Do they pee from their BALLS?!?\"\n/cc @overheardathome",
        "id": 88463704835887100,
        "retweet_count": 26,
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "source": "<a href=\"http://tweetlogix.com\" rel=\"nofollow\">Tweetlogix</a>",
        "in_reply_to_screen_name": null,
        "user": {
            "profile_sidebar_fill_color": "b8aa9c",
            "profile_sidebar_border_color": "b8aa9c",
            "name": "Scott Hanselman",
            "profile_background_tile": true,
            "location": "Portland, Oregon",
            "profile_image_url": "http://a2.twimg.com/profile_images/1425619283/image_normal.jpg",
            "created_at": "Tue May 01 05:55:26 +0000 2007",
            "follow_request_sent": false,
            "profile_link_color": "72412c",
            "is_translator": false,
            "id_str": 5676102,
            "default_profile": false,
            "contributors_enabled": false,
            "favourites_count": 2336,
            "url": "http://hanselman.com",
            "id": 5676102,
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1425619283/image_normal.jpg",
            "utc_offset": "-28800",
            "listed_count": 4063,
            "profile_use_background_image": true,
            "lang": "en",
            "profile_text_color": 696969,
            "followers_count": 38832,
            "protected": false,
            "profile_background_color": "d1cdc1",
            "description": "Tech, Diabetes, Parenting, Race, Linguistics, Fashion, Podcasting, Media, Culture, Code, Ratchet.",
            "time_zone": "Pacific Time (US & Canada)",
            "verified": false,
            "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "notifications": false,
            "geo_enabled": true,
            "friends_count": 2695,
            "profile_background_image_url": "http://a3.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "statuses_count": 44794,
            "default_profile_image": false,
            "screen_name": "shanselman",
            "following": true,
            "show_all_inline_media": true
        },
        "place": null,
        "in_reply_to_status_id": null
    },
    {
        "coordinates": null,
        "truncated": false,
        "created_at": "Wed Jul 06 04:13:18 +0000 2011",
        "favorited": false,
        "id_str": 88460488693907460,
        "entities": {
            "urls": [],
            "hashtags": [],
            "user_mentions": []
        },
        "in_reply_to_user_id_str": null,
        "contributors": null,
        "text": "I've decided to unfollow myself. I'm far too clever for my own good with too many diverse interests.",
        "id": 88460488693907460,
        "retweet_count": 9,
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "source": "<a href=\"http://tweetlogix.com\" rel=\"nofollow\">Tweetlogix</a>",
        "in_reply_to_screen_name": null,
        "user": {
            "profile_sidebar_fill_color": "b8aa9c",
            "profile_sidebar_border_color": "b8aa9c",
            "name": "Scott Hanselman",
            "profile_background_tile": true,
            "location": "Portland, Oregon",
            "profile_image_url": "http://a2.twimg.com/profile_images/1425619283/image_normal.jpg",
            "created_at": "Tue May 01 05:55:26 +0000 2007",
            "follow_request_sent": false,
            "is_translator": false,
            "profile_link_color": "72412c",
            "id_str": 5676102,
            "default_profile": false,
            "favourites_count": 2336,
            "contributors_enabled": false,
            "url": "http://hanselman.com",
            "id": 5676102,
            "utc_offset": "-28800",
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1425619283/image_normal.jpg",
            "profile_use_background_image": true,
            "listed_count": 4063,
            "lang": "en",
            "profile_text_color": 696969,
            "followers_count": 38832,
            "protected": false,
            "profile_background_color": "d1cdc1",
            "geo_enabled": true,
            "description": "Tech, Diabetes, Parenting, Race, Linguistics, Fashion, Podcasting, Media, Culture, Code, Ratchet.",
            "time_zone": "Pacific Time (US & Canada)",
            "verified": false,
            "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "notifications": false,
            "friends_count": 2695,
            "statuses_count": 44794,
            "profile_background_image_url": "http://a3.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "default_profile_image": false,
            "screen_name": "shanselman",
            "show_all_inline_media": true,
            "following": true
        },
        "place": null,
        "in_reply_to_status_id": null
    },
    {
        "coordinates": null,
        "truncated": false,
        "created_at": "Wed Jul 06 03:31:21 +0000 2011",
        "favorited": false,
        "retweeted_status": {
            "coordinates": null,
            "truncated": false,
            "created_at": "Wed Jul 06 02:39:58 +0000 2011",
            "favorited": false,
            "id_str": 88436998230130690,
            "entities": {
                "urls": [{
                    "expanded_url": "http://www.jeff.wilcox.name/2011/07/slm-perf-blog/",
                    "url": "http://t.co/UZa9xkn",
                    "indices": [66, 85],
                    "display_url": "jeff.wilcox.name/2011/07/slm-pe\u2026"
                }],
                "hashtags": [{
                    "text": "wp7dev",
                    "indices": [86, 93]
                }],
                "user_mentions": []
            },
            "in_reply_to_user_id_str": null,
            "contributors": null,
            "text": "Blogged links to the Mango Silverlight performance guidance posts http://t.co/UZa9xkn #wp7dev",
            "id": 88436998230130690,
            "retweet_count": 17,
            "in_reply_to_status_id_str": null,
            "geo": null,
            "retweeted": false,
            "in_reply_to_user_id": null,
            "source": "web",
            "in_reply_to_screen_name": null,
            "user": {
                "profile_sidebar_fill_color": 252429,
                "profile_sidebar_border_color": "181A1E",
                "name": "Jeff Wilcox",
                "profile_background_tile": false,
                "location": "Seattle, WA",
                "profile_image_url": "http://a0.twimg.com/profile_images/1300437195/JeffOnWhite_normal.jpg",
                "created_at": "Mon Apr 23 15:21:49 +0000 2007",
                "is_translator": false,
                "profile_link_color": "2FC2EF",
                "id_str": 5435752,
                "follow_request_sent": false,
                "contributors_enabled": false,
                "favourites_count": 8,
                "default_profile": false,
                "url": "http://www.jeff.wilcox.name/",
                "id": 5435752,
                "profile_image_url_https": "https://si0.twimg.com/profile_images/1300437195/JeffOnWhite_normal.jpg",
                "utc_offset": "-28800",
                "profile_use_background_image": true,
                "listed_count": 171,
                "lang": "en",
                "profile_text_color": 666666,
                "followers_count": 2503,
                "protected": false,
                "profile_background_color": "1A1B1F",
                "geo_enabled": true,
                "description": "Senior Developer on Silverlight for Windows Phone at Microsoft. Author of the 4th & Mayor foursquare\u2122 app. Imported from Detroit. University of Michigan alum.",
                "time_zone": "Pacific Time (US & Canada)",
                "verified": false,
                "profile_background_image_url_https": "https://si0.twimg.com/images/themes/theme9/bg.gif",
                "notifications": false,
                "friends_count": 185,
                "statuses_count": 4918,
                "default_profile_image": false,
                "profile_background_image_url": "http://a1.twimg.com/images/themes/theme9/bg.gif",
                "screen_name": "jeffwilcox",
                "show_all_inline_media": false,
                "following": false
            },
            "place": null,
            "in_reply_to_status_id": null
        },
        "id_str": 88449932280860670,
        "entities": {
            "urls": [{
                "expanded_url": "http://www.jeff.wilcox.name/2011/07/slm-perf-blog/",
                "url": "http://t.co/UZa9xkn",
                "indices": [82, 101],
                "display_url": "jeff.wilcox.name/2011/07/slm-pe\u2026"
            }],
            "hashtags": [{
                "text": "wp7dev",
                "indices": [102, 109]
            }],
            "user_mentions": [{
                "name": "Jeff Wilcox",
                "id_str": 5435752,
                "id": 5435752,
                "indices": [3, 14],
                "screen_name": "jeffwilcox"
            }]
        },
        "in_reply_to_user_id_str": null,
        "contributors": null,
        "text": "RT @jeffwilcox: Blogged links to the Mango Silverlight performance guidance posts http://t.co/UZa9xkn #wp7dev",
        "id": 88449932280860670,
        "retweet_count": 17,
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "source": "<a href=\"http://seesmic.com/seesmic_mobile/wp7/\" rel=\"nofollow\">Seesmic for Windows Phone 7</a>",
        "in_reply_to_screen_name": null,
        "user": {
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_sidebar_border_color": "C0DEED",
            "name": "Scott Guthrie",
            "profile_background_tile": false,
            "location": "Redmond, WA",
            "profile_image_url": "http://a0.twimg.com/profile_images/565139568/redshirt_normal.jpg",
            "created_at": "Fri May 22 04:39:35 +0000 2009",
            "is_translator": false,
            "profile_link_color": "0084B4",
            "id_str": 41754227,
            "follow_request_sent": false,
            "contributors_enabled": false,
            "favourites_count": 43,
            "default_profile": true,
            "url": "http://weblogs.asp.net/scottgu",
            "id": 41754227,
            "profile_image_url_https": "https://si0.twimg.com/profile_images/565139568/redshirt_normal.jpg",
            "utc_offset": "-28800",
            "profile_use_background_image": true,
            "listed_count": 3879,
            "lang": "en",
            "profile_text_color": 333333,
            "followers_count": 45114,
            "protected": false,
            "profile_background_color": "C0DEED",
            "geo_enabled": false,
            "description": "I live in Seattle and build a few products for Microsoft",
            "time_zone": "Pacific Time (US & Canada)",
            "verified": false,
            "profile_background_image_url_https": "https://si0.twimg.com/images/themes/theme1/bg.png",
            "notifications": false,
            "friends_count": 80,
            "statuses_count": 2758,
            "default_profile_image": false,
            "profile_background_image_url": "http://a0.twimg.com/images/themes/theme1/bg.png",
            "screen_name": "scottgu",
            "show_all_inline_media": false,
            "following": true
        },
        "place": null,
        "in_reply_to_status_id": null
    },
    {
        "coordinates": null,
        "truncated": true,
        "created_at": "Wed Jul 06 02:35:01 +0000 2011",
        "favorited": false,
        "retweeted_status": {
            "coordinates": null,
            "truncated": false,
            "created_at": "Wed Jul 06 02:24:03 +0000 2011",
            "favorited": false,
            "id_str": 88432992837582850,
            "entities": {
                "urls": [{
                    "expanded_url": "http://getglimpse.com",
                    "url": "http://t.co/ANqUPu8",
                    "indices": [37, 56],
                    "display_url": "getglimpse.com"
                }],
                "hashtags": [],
                "user_mentions": []
            },
            "in_reply_to_user_id_str": null,
            "contributors": null,
            "text": "If you're an MVC developer check out http://t.co/ANqUPu8 to see route matching, view engine, action filter pipeline, child rendering etc...",
            "id": 88432992837582850,
            "retweet_count": 74,
            "in_reply_to_status_id_str": null,
            "geo": null,
            "retweeted": false,
            "in_reply_to_user_id": null,
            "source": "web",
            "in_reply_to_screen_name": null,
            "user": {
                "profile_sidebar_fill_color": "cccccc",
                "profile_sidebar_border_color": 0,
                "name": "Damien Guard",
                "profile_background_tile": true,
                "location": "Bellevue, Washington",
                "profile_image_url": "http://a3.twimg.com/profile_images/1282843786/download_normal.jpg",
                "created_at": "Mon Jan 21 14:28:40 +0000 2008",
                "is_translator": false,
                "profile_link_color": "0000ff",
                "id_str": 12494542,
                "follow_request_sent": false,
                "default_profile": false,
                "contributors_enabled": false,
                "favourites_count": 1,
                "url": "http://damieng.com",
                "id": 12494542,
                "utc_offset": "-28800",
                "profile_image_url_https": "https://si0.twimg.com/profile_images/1282843786/download_normal.jpg",
                "profile_use_background_image": true,
                "listed_count": 160,
                "lang": "en",
                "profile_text_color": 0,
                "followers_count": 1755,
                "protected": false,
                "profile_background_color": 333333,
                "description": "I'm Developer at Microsoft on Xbox.com (previously LINQ to SQL/EF/CodeFirst). Font geek, retro gamer & occasional blogger.",
                "time_zone": "Pacific Time (US & Canada)",
                "geo_enabled": true,
                "verified": false,
                "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/2726511/background.gif",
                "notifications": false,
                "friends_count": 844,
                "default_profile_image": false,
                "profile_background_image_url": "http://a0.twimg.com/profile_background_images/2726511/background.gif",
                "statuses_count": 3173,
                "screen_name": "damienguard",
                "following": false,
                "show_all_inline_media": false
            },
            "place": null,
            "in_reply_to_status_id": null
        },
        "id_str": 88435755164246020,
        "entities": {
            "urls": [{
                "expanded_url": "http://getglimpse.com",
                "url": "http://t.co/ANqUPu8",
                "indices": [54, 73],
                "display_url": "getglimpse.com"
            }],
            "hashtags": [],
            "user_mentions": [{
                "name": "Damien Guard",
                "id_str": 12494542,
                "id": 12494542,
                "indices": [3, 15],
                "screen_name": "damienguard"
            }]
        },
        "in_reply_to_user_id_str": null,
        "contributors": null,
        "text": "RT @damienguard: If you're an MVC developer check out http://t.co/ANqUPu8 to see route matching, view engine, action filter pipeline, ch ...",
        "id": 88435755164246020,
        "retweet_count": 74,
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "source": "web",
        "in_reply_to_screen_name": null,
        "user": {
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_sidebar_border_color": "C0DEED",
            "name": "Scott Guthrie",
            "profile_background_tile": false,
            "location": "Redmond, WA",
            "profile_image_url": "http://a0.twimg.com/profile_images/565139568/redshirt_normal.jpg",
            "created_at": "Fri May 22 04:39:35 +0000 2009",
            "is_translator": false,
            "profile_link_color": "0084B4",
            "id_str": 41754227,
            "follow_request_sent": false,
            "default_profile": true,
            "contributors_enabled": false,
            "favourites_count": 43,
            "url": "http://weblogs.asp.net/scottgu",
            "id": 41754227,
            "utc_offset": "-28800",
            "profile_image_url_https": "https://si0.twimg.com/profile_images/565139568/redshirt_normal.jpg",
            "profile_use_background_image": true,
            "listed_count": 3880,
            "lang": "en",
            "profile_text_color": 333333,
            "followers_count": 45116,
            "protected": false,
            "profile_background_color": "C0DEED",
            "description": "I live in Seattle and build a few products for Microsoft",
            "time_zone": "Pacific Time (US & Canada)",
            "geo_enabled": false,
            "verified": false,
            "profile_background_image_url_https": "https://si0.twimg.com/images/themes/theme1/bg.png",
            "notifications": false,
            "friends_count": 80,
            "default_profile_image": false,
            "profile_background_image_url": "http://a0.twimg.com/images/themes/theme1/bg.png",
            "statuses_count": 2758,
            "screen_name": "scottgu",
            "following": true,
            "show_all_inline_media": false
        },
        "place": null,
        "in_reply_to_status_id": null
    },
    {
        "coordinates": null,
        "truncated": false,
        "created_at": "Tue Jul 05 23:12:29 +0000 2011",
        "favorited": false,
        "retweeted_status": {
            "coordinates": null,
            "truncated": false,
            "created_at": "Tue Jul 05 23:12:01 +0000 2011",
            "favorited": false,
            "id_str": 88384665433542660,
            "entities": {
                "urls": [{
                    "expanded_url": null,
                    "url": "http://tnw.co/o8a5IV",
                    "indices": [85, 105]
                }],
                "hashtags": [],
                "user_mentions": [{
                    "name": "(jeff)isageek",
                    "id_str": 2900,
                    "id": 2900,
                    "indices": [7, 19],
                    "screen_name": "jeffisageek"
                }]
            },
            "in_reply_to_user_id_str": null,
            "contributors": null,
            "text": "Oh. RT @jeffisageek: check it..  As of July 31st, all Google profiles will be public http://tnw.co/o8a5IV",
            "id": 88384665433542660,
            "retweet_count": 19,
            "in_reply_to_status_id_str": null,
            "geo": null,
            "retweeted": false,
            "in_reply_to_user_id": null,
            "source": "<a href=\"http://www.tweetdeck.com\" rel=\"nofollow\">TweetDeck</a>",
            "in_reply_to_screen_name": null,
            "user": {
                "profile_sidebar_fill_color": "7AC3EE",
                "profile_sidebar_border_color": "65B0DA",
                "name": "Dr. Goddess",
                "profile_background_tile": true,
                "location": "The Burgh",
                "profile_image_url": "http://a3.twimg.com/profile_images/1372969762/91c7a36f-0f3f-4fb7-b1fe-651c4f1973c0_normal.png",
                "created_at": "Sat Jan 24 23:05:24 +0000 2009",
                "follow_request_sent": false,
                "profile_link_color": "FF0000",
                "is_translator": false,
                "id_str": 19468168,
                "default_profile": false,
                "favourites_count": 1160,
                "contributors_enabled": false,
                "url": "http://drgoddess.com",
                "id": 19468168,
                "utc_offset": "-18000",
                "profile_image_url_https": "https://si0.twimg.com/profile_images/1372969762/91c7a36f-0f3f-4fb7-b1fe-651c4f1973c0_normal.png",
                "listed_count": 392,
                "profile_use_background_image": true,
                "lang": "en",
                "profile_text_color": "3D1957",
                "followers_count": 5697,
                "protected": false,
                "geo_enabled": false,
                "profile_background_color": "642D8B",
                "description": "American & Africana Studies Scholar. Artist. Activist. Blogger. Tech Lover. Traveler. Reality TV Snark. Creator of #BaracksFlagPin #GradChat & #FoodiesUnite.",
                "time_zone": "Eastern Time (US & Canada)",
                "verified": false,
                "profile_background_image_url_https": "https://si0.twimg.com/images/themes/theme10/bg.gif",
                "notifications": false,
                "friends_count": 2597,
                "statuses_count": 105284,
                "profile_background_image_url": "http://a1.twimg.com/images/themes/theme10/bg.gif",
                "default_profile_image": false,
                "screen_name": "drgoddess",
                "show_all_inline_media": true,
                "following": false
            },
            "place": null,
            "in_reply_to_status_id": null
        },
        "id_str": 88384786103676930,
        "entities": {
            "urls": [{
                "expanded_url": null,
                "url": "http://tnw.co/o8a5IV",
                "indices": [100, 120]
            }],
            "hashtags": [],
            "user_mentions": [{
                "name": "Dr. Goddess",
                "id_str": 19468168,
                "id": 19468168,
                "indices": [3, 13],
                "screen_name": "drgoddess"
            },
            {
                "name": "(jeff)isageek",
                "id_str": 2900,
                "id": 2900,
                "indices": [22, 34],
                "screen_name": "jeffisageek"
            }]
        },
        "in_reply_to_user_id_str": null,
        "contributors": null,
        "text": "RT @drgoddess: Oh. RT @jeffisageek: check it..  As of July 31st, all Google profiles will be public http://tnw.co/o8a5IV",
        "id": 88384786103676930,
        "retweet_count": 19,
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "source": "web",
        "in_reply_to_screen_name": null,
        "user": {
            "profile_sidebar_fill_color": "b8aa9c",
            "profile_sidebar_border_color": "b8aa9c",
            "name": "Scott Hanselman",
            "profile_background_tile": true,
            "location": "Portland, Oregon",
            "profile_image_url": "http://a2.twimg.com/profile_images/1425619283/image_normal.jpg",
            "created_at": "Tue May 01 05:55:26 +0000 2007",
            "follow_request_sent": false,
            "profile_link_color": "72412c",
            "is_translator": false,
            "id_str": 5676102,
            "default_profile": false,
            "favourites_count": 2336,
            "contributors_enabled": false,
            "url": "http://hanselman.com",
            "id": 5676102,
            "utc_offset": "-28800",
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1425619283/image_normal.jpg",
            "listed_count": 4063,
            "profile_use_background_image": true,
            "lang": "en",
            "profile_text_color": 696969,
            "followers_count": 38830,
            "protected": false,
            "geo_enabled": true,
            "profile_background_color": "d1cdc1",
            "description": "Tech, Diabetes, Parenting, Race, Linguistics, Fashion, Podcasting, Media, Culture, Code, Ratchet.",
            "time_zone": "Pacific Time (US & Canada)",
            "verified": false,
            "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "notifications": false,
            "friends_count": 2695,
            "statuses_count": 44794,
            "profile_background_image_url": "http://a3.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "default_profile_image": false,
            "screen_name": "shanselman",
            "show_all_inline_media": true,
            "following": true
        },
        "place": null,
        "in_reply_to_status_id": null
    },
    {
        "coordinates": null,
        "truncated": false,
        "created_at": "Tue Jul 05 21:36:01 +0000 2011",
        "favorited": false,
        "retweeted_status": {
            "coordinates": null,
            "truncated": false,
            "created_at": "Tue Jul 05 21:30:19 +0000 2011",
            "favorited": false,
            "id_str": 88359074546192380,
            "entities": {
                "urls": [],
                "hashtags": [],
                "user_mentions": [{
                    "name": "Scott Hanselman",
                    "id_str": 5676102,
                    "id": 5676102,
                    "indices": [39, 50],
                    "screen_name": "shanselman"
                }]
            },
            "in_reply_to_user_id_str": null,
            "contributors": null,
            "text": "reading up on powershell and landed on @shanselman's page. i thought he was just some wise-ass from the internet.",
            "id": 88359074546192380,
            "retweet_count": 6,
            "in_reply_to_status_id_str": null,
            "geo": null,
            "retweeted": false,
            "in_reply_to_user_id": null,
            "source": "<a href=\"http://www.echofon.com/\" rel=\"nofollow\">Echofon</a>",
            "in_reply_to_screen_name": null,
            "user": {
                "profile_sidebar_fill_color": "fff7eb",
                "profile_sidebar_border_color": "43AFD2",
                "name": "bee effin aye'ch",
                "profile_background_tile": false,
                "location": "phila, period.",
                "profile_image_url": "http://a2.twimg.com/profile_images/1321346283/SPD360c_normal.png",
                "created_at": "Thu Sep 27 19:15:01 +0000 2007",
                "follow_request_sent": false,
                "is_translator": false,
                "profile_link_color": "34c2c7",
                "id_str": 9129902,
                "contributors_enabled": false,
                "favourites_count": 6,
                "default_profile": false,
                "url": "http://at.yamomzcrib.com",
                "id": 9129902,
                "profile_image_url_https": "https://si0.twimg.com/profile_images/1321346283/SPD360c_normal.png",
                "utc_offset": "-18000",
                "profile_use_background_image": true,
                "listed_count": 21,
                "lang": "en",
                "profile_text_color": 51824,
                "followers_count": 404,
                "protected": false,
                "profile_background_color": "EFEFEF",
                "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/244351101/xe1cdb97f759e1cc93084d0c616370c9.gif",
                "description": "i recognize patterns. sometimes, i point them out to others. in my spare time, i crack jokes about your mom - http://yourmomisclubbin.com",
                "time_zone": "Eastern Time (US & Canada)",
                "verified": false,
                "geo_enabled": false,
                "notifications": false,
                "profile_background_image_url": "http://a0.twimg.com/profile_background_images/244351101/xe1cdb97f759e1cc93084d0c616370c9.gif",
                "statuses_count": 9638,
                "default_profile_image": false,
                "friends_count": 248,
                "screen_name": "bfnh",
                "following": false,
                "show_all_inline_media": false
            },
            "place": null,
            "in_reply_to_status_id": null
        },
        "id_str": 88360508423544830,
        "entities": {
            "urls": [],
            "hashtags": [],
            "user_mentions": [{
                "name": "bee effin aye'ch",
                "id_str": 9129902,
                "id": 9129902,
                "indices": [3, 8],
                "screen_name": "bfnh"
            },
            {
                "name": "Scott Hanselman",
                "id_str": 5676102,
                "id": 5676102,
                "indices": [49, 60],
                "screen_name": "shanselman"
            }]
        },
        "in_reply_to_user_id_str": null,
        "contributors": null,
        "text": "RT @bfnh: reading up on powershell and landed on @shanselman's page. i thought he was just some wise-ass from the internet.",
        "id": 88360508423544830,
        "retweet_count": 6,
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "source": "web",
        "in_reply_to_screen_name": null,
        "user": {
            "profile_sidebar_fill_color": "b8aa9c",
            "profile_sidebar_border_color": "b8aa9c",
            "name": "Scott Hanselman",
            "profile_background_tile": true,
            "location": "Portland, Oregon",
            "profile_image_url": "http://a2.twimg.com/profile_images/1425619283/image_normal.jpg",
            "created_at": "Tue May 01 05:55:26 +0000 2007",
            "follow_request_sent": false,
            "is_translator": false,
            "profile_link_color": "72412c",
            "id_str": 5676102,
            "contributors_enabled": false,
            "favourites_count": 2336,
            "default_profile": false,
            "url": "http://hanselman.com",
            "id": 5676102,
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1425619283/image_normal.jpg",
            "utc_offset": "-28800",
            "profile_use_background_image": true,
            "listed_count": 4063,
            "lang": "en",
            "profile_text_color": 696969,
            "followers_count": 38830,
            "protected": false,
            "profile_background_color": "d1cdc1",
            "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "description": "Tech, Diabetes, Parenting, Race, Linguistics, Fashion, Podcasting, Media, Culture, Code, Ratchet.",
            "time_zone": "Pacific Time (US & Canada)",
            "verified": false,
            "geo_enabled": true,
            "notifications": false,
            "profile_background_image_url": "http://a3.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "statuses_count": 44794,
            "default_profile_image": false,
            "friends_count": 2695,
            "screen_name": "shanselman",
            "following": true,
            "show_all_inline_media": true
        },
        "place": null,
        "in_reply_to_status_id": null
    },
    {
        "coordinates": null,
        "created_at": "Tue Jul 05 21:17:28 +0000 2011",
        "truncated": false,
        "favorited": false,
        "retweeted_status": {
            "coordinates": null,
            "created_at": "Tue Jul 05 20:49:50 +0000 2011",
            "truncated": false,
            "favorited": false,
            "id_str": 88348887693279230,
            "in_reply_to_user_id_str": null,
            "entities": {
                "urls": [],
                "hashtags": [],
                "user_mentions": [{
                    "name": "Scott Hanselman",
                    "id_str": 5676102,
                    "id": 5676102,
                    "indices": [34, 45],
                    "screen_name": "shanselman"
                }]
            },
            "contributors": null,
            "text": "I just unfollowed and re-followed @shanselman. It's the cool thing to do today. I think I'll do it again right now...",
            "id": 88348887693279230,
            "retweet_count": 7,
            "in_reply_to_status_id_str": null,
            "geo": null,
            "retweeted": false,
            "in_reply_to_user_id": null,
            "user": {
                "name": "Rob Conery",
                "profile_sidebar_border_color": "181A1E",
                "profile_background_tile": false,
                "profile_sidebar_fill_color": 252429,
                "created_at": "Mon Feb 07 19:50:05 +0000 2011",
                "location": "Hanalei, HI",
                "profile_image_url": "http://a2.twimg.com/profile_images/1254541372/Screen_shot_2011-02-07_at_9.59.27_AM_normal.png",
                "profile_link_color": "2FC2EF",
                "id_str": 248815441,
                "follow_request_sent": false,
                "is_translator": false,
                "default_profile": false,
                "url": "http://wekeroad.com",
                "favourites_count": 8,
                "contributors_enabled": false,
                "utc_offset": "-36000",
                "id": 248815441,
                "profile_image_url_https": "https://si0.twimg.com/profile_images/1254541372/Screen_shot_2011-02-07_at_9.59.27_AM_normal.png",
                "profile_use_background_image": true,
                "listed_count": 149,
                "protected": false,
                "followers_count": 3284,
                "lang": "en",
                "profile_text_color": 666666,
                "profile_background_color": "1A1B1F",
                "time_zone": "Hawaii",
                "verified": false,
                "geo_enabled": false,
                "profile_background_image_url_https": "https://si0.twimg.com/images/themes/theme9/bg.gif",
                "notifications": false,
                "description": "Co-founder of Tekpub, Ruby and C# enthusiast. Dogma assasin and disrupter of corporate think-speak. Bad spleller.",
                "friends_count": 44,
                "profile_background_image_url": "http://a1.twimg.com/images/themes/theme9/bg.gif",
                "default_profile_image": false,
                "statuses_count": 2024,
                "following": false,
                "screen_name": "robconery",
                "show_all_inline_media": false
            },
            "place": null,
            "in_reply_to_screen_name": null,
            "source": "<a href=\"http://itunes.apple.com/us/app/twitter/id409789998?mt=12\" rel=\"nofollow\">Twitter for Mac</a>",
            "in_reply_to_status_id": null
        },
        "id_str": 88355838640664580,
        "in_reply_to_user_id_str": null,
        "entities": {
            "urls": [],
            "hashtags": [],
            "user_mentions": [{
                "name": "Rob Conery",
                "id_str": 248815441,
                "id": 248815441,
                "indices": [3, 13],
                "screen_name": "robconery"
            },
            {
                "name": "Scott Hanselman",
                "id_str": 5676102,
                "id": 5676102,
                "indices": [49, 60],
                "screen_name": "shanselman"
            }]
        },
        "contributors": null,
        "text": "RT @robconery: I just unfollowed and re-followed @shanselman. It's the cool thing to do today. I think I'll do it again right now...",
        "id": 88355838640664580,
        "retweet_count": 7,
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "user": {
            "name": "Scott Hanselman",
            "profile_sidebar_border_color": "b8aa9c",
            "profile_background_tile": true,
            "profile_sidebar_fill_color": "b8aa9c",
            "created_at": "Tue May 01 05:55:26 +0000 2007",
            "location": "Portland, Oregon",
            "profile_image_url": "http://a2.twimg.com/profile_images/1425619283/image_normal.jpg",
            "profile_link_color": "72412c",
            "id_str": 5676102,
            "follow_request_sent": false,
            "is_translator": false,
            "default_profile": false,
            "url": "http://hanselman.com",
            "favourites_count": 2336,
            "contributors_enabled": false,
            "utc_offset": "-28800",
            "id": 5676102,
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1425619283/image_normal.jpg",
            "profile_use_background_image": true,
            "listed_count": 4063,
            "protected": false,
            "followers_count": 38833,
            "lang": "en",
            "profile_text_color": 696969,
            "profile_background_color": "d1cdc1",
            "time_zone": "Pacific Time (US & Canada)",
            "verified": false,
            "geo_enabled": true,
            "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "notifications": false,
            "description": "Tech, Diabetes, Parenting, Race, Linguistics, Fashion, Podcasting, Media, Culture, Code, Ratchet.",
            "friends_count": 2695,
            "profile_background_image_url": "http://a3.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "default_profile_image": false,
            "statuses_count": 44794,
            "following": true,
            "screen_name": "shanselman",
            "show_all_inline_media": true
        },
        "place": null,
        "in_reply_to_screen_name": null,
        "source": "web",
        "in_reply_to_status_id": null
    },
    {
        "coordinates": null,
        "truncated": false,
        "created_at": "Tue Jul 05 21:10:57 +0000 2011",
        "favorited": false,
        "retweeted_status": {
            "coordinates": null,
            "truncated": false,
            "created_at": "Tue Jul 05 20:27:29 +0000 2011",
            "favorited": false,
            "id_str": 88343260661166080,
            "entities": {
                "urls": [{
                    "expanded_url": null,
                    "url": "http://i.imgur.com/HuK6e.jpg",
                    "indices": [22, 50]
                }],
                "hashtags": [],
                "user_mentions": [{
                    "name": "Scott Hanselman",
                    "id_str": 5676102,
                    "id": 5676102,
                    "indices": [0, 11],
                    "screen_name": "shanselman"
                }]
            },
            "in_reply_to_user_id_str": 5676102,
            "contributors": null,
            "text": "@shanselman too much? http://i.imgur.com/HuK6e.jpg",
            "id": 88343260661166080,
            "retweet_count": 20,
            "in_reply_to_status_id_str": 88322162691285000,
            "geo": null,
            "retweeted": false,
            "in_reply_to_user_id": 5676102,
            "source": "<a href=\"http://www.tweetdeck.com\" rel=\"nofollow\">TweetDeck</a>",
            "in_reply_to_screen_name": "shanselman",
            "user": {
                "profile_sidebar_fill_color": "dddddd",
                "profile_sidebar_border_color": "87bc44",
                "name": "Juan Manuel Formoso",
                "profile_background_tile": false,
                "location": "Buenos Aires, Argentina",
                "profile_image_url": "http://a2.twimg.com/profile_images/1330623064/yo_4_normal.png",
                "created_at": "Wed Jun 11 21:04:18 +0000 2008",
                "follow_request_sent": false,
                "is_translator": false,
                "profile_link_color": "0000ff",
                "id_str": 15089227,
                "default_profile": false,
                "favourites_count": 6,
                "contributors_enabled": false,
                "url": "http://juanformoso.com.ar",
                "id": 15089227,
                "utc_offset": "-10800",
                "profile_image_url_https": "https://si0.twimg.com/profile_images/1330623064/yo_4_normal.png",
                "profile_use_background_image": true,
                "listed_count": 17,
                "lang": "en",
                "profile_text_color": 0,
                "followers_count": 141,
                "protected": false,
                "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/94988015/twit_back1.PNG",
                "profile_background_color": "cccccc",
                "description": "Senior geek; Software crafter; Gaming junkie.",
                "time_zone": "Buenos Aires",
                "verified": false,
                "geo_enabled": true,
                "notifications": false,
                "friends_count": 48,
                "profile_background_image_url": "http://a0.twimg.com/profile_background_images/94988015/twit_back1.PNG",
                "default_profile_image": false,
                "statuses_count": 2605,
                "screen_name": "juanformoso",
                "following": false,
                "show_all_inline_media": false
            },
            "place": null,
            "in_reply_to_status_id": 88322162691285000
        },
        "id_str": 88354199179501570,
        "entities": {
            "urls": [{
                "expanded_url": null,
                "url": "http://i.imgur.com/HuK6e.jpg",
                "indices": [39, 67]
            }],
            "hashtags": [],
            "user_mentions": [{
                "name": "Juan Manuel Formoso",
                "id_str": 15089227,
                "id": 15089227,
                "indices": [3, 15],
                "screen_name": "juanformoso"
            },
            {
                "name": "Scott Hanselman",
                "id_str": 5676102,
                "id": 5676102,
                "indices": [17, 28],
                "screen_name": "shanselman"
            }]
        },
        "in_reply_to_user_id_str": null,
        "contributors": null,
        "text": "RT @juanformoso: @shanselman too much? http://i.imgur.com/HuK6e.jpg",
        "id": 88354199179501570,
        "retweet_count": 20,
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "source": "web",
        "in_reply_to_screen_name": null,
        "user": {
            "profile_sidebar_fill_color": "b8aa9c",
            "profile_sidebar_border_color": "b8aa9c",
            "name": "Scott Hanselman",
            "profile_background_tile": true,
            "location": "Portland, Oregon",
            "profile_image_url": "http://a2.twimg.com/profile_images/1425619283/image_normal.jpg",
            "created_at": "Tue May 01 05:55:26 +0000 2007",
            "follow_request_sent": false,
            "is_translator": false,
            "profile_link_color": "72412c",
            "id_str": 5676102,
            "default_profile": false,
            "favourites_count": 2336,
            "contributors_enabled": false,
            "url": "http://hanselman.com",
            "id": 5676102,
            "utc_offset": "-28800",
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1425619283/image_normal.jpg",
            "profile_use_background_image": true,
            "listed_count": 4063,
            "lang": "en",
            "profile_text_color": 696969,
            "followers_count": 38833,
            "protected": false,
            "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "profile_background_color": "d1cdc1",
            "description": "Tech, Diabetes, Parenting, Race, Linguistics, Fashion, Podcasting, Media, Culture, Code, Ratchet.",
            "time_zone": "Pacific Time (US & Canada)",
            "verified": false,
            "geo_enabled": true,
            "notifications": false,
            "friends_count": 2695,
            "profile_background_image_url": "http://a3.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "default_profile_image": false,
            "statuses_count": 44794,
            "screen_name": "shanselman",
            "following": true,
            "show_all_inline_media": true
        },
        "place": null,
        "in_reply_to_status_id": null
    },
    {
        "coordinates": null,
        "truncated": false,
        "created_at": "Tue Jul 05 20:52:20 +0000 2011",
        "favorited": false,
        "id_str": 88349516587216900,
        "entities": {
            "urls": [{
                "expanded_url": "http://www.hanselman.com/blog/TwoMustHaveToolsForAMoreReadableWeb.aspx",
                "url": "http://t.co/HBcnidB",
                "indices": [85, 104],
                "display_url": "hanselman.com/blog/TwoMustHa\u2026"
            }],
            "hashtags": [],
            "user_mentions": []
        },
        "in_reply_to_user_id_str": null,
        "contributors": null,
        "text": "Do you have more than 5 tabs open? STOP. Two Must-Have Tools for a More Readable Web http://t.co/HBcnidB",
        "id": 88349516587216900,
        "retweet_count": 40,
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "source": "<a href=\"http://twitter.com/tweetbutton\" rel=\"nofollow\">Tweet Button</a>",
        "in_reply_to_screen_name": null,
        "user": {
            "profile_sidebar_fill_color": "b8aa9c",
            "profile_sidebar_border_color": "b8aa9c",
            "name": "Scott Hanselman",
            "profile_background_tile": true,
            "location": "Portland, Oregon",
            "profile_image_url": "http://a2.twimg.com/profile_images/1425619283/image_normal.jpg",
            "created_at": "Tue May 01 05:55:26 +0000 2007",
            "follow_request_sent": false,
            "profile_link_color": "72412c",
            "is_translator": false,
            "id_str": 5676102,
            "contributors_enabled": false,
            "default_profile": false,
            "favourites_count": 2336,
            "url": "http://hanselman.com",
            "id": 5676102,
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1425619283/image_normal.jpg",
            "utc_offset": "-28800",
            "listed_count": 4063,
            "profile_use_background_image": true,
            "lang": "en",
            "profile_text_color": 696969,
            "followers_count": 38830,
            "protected": false,
            "profile_background_color": "d1cdc1",
            "description": "Tech, Diabetes, Parenting, Race, Linguistics, Fashion, Podcasting, Media, Culture, Code, Ratchet.",
            "time_zone": "Pacific Time (US & Canada)",
            "verified": false,
            "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "notifications": false,
            "geo_enabled": true,
            "friends_count": 2695,
            "profile_background_image_url": "http://a3.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "statuses_count": 44794,
            "default_profile_image": false,
            "screen_name": "shanselman",
            "following": true,
            "show_all_inline_media": true
        },
        "place": null,
        "in_reply_to_status_id": null
    },
    {
        "coordinates": null,
        "truncated": false,
        "created_at": "Tue Jul 05 20:02:34 +0000 2011",
        "favorited": false,
        "retweeted_status": {
            "coordinates": null,
            "truncated": false,
            "created_at": "Tue Jul 05 20:02:24 +0000 2011",
            "favorited": false,
            "id_str": 88336949550653440,
            "entities": {
                "urls": [],
                "hashtags": [],
                "user_mentions": [{
                    "name": "Scott Hanselman",
                    "id_str": 5676102,
                    "id": 5676102,
                    "indices": [0, 11],
                    "screen_name": "shanselman"
                }]
            },
            "in_reply_to_user_id_str": 5676102,
            "contributors": null,
            "text": "@shanselman I used to think you tweeted a lot.  Then I followed a bunch more people and now I barely see you.",
            "id": 88336949550653440,
            "retweet_count": 4,
            "in_reply_to_status_id_str": 88333728409063420,
            "geo": null,
            "retweeted": false,
            "in_reply_to_user_id": 5676102,
            "source": "<a href=\"http://itunes.apple.com/us/app/twitter/id409789998?mt=12\" rel=\"nofollow\">Twitter for Mac</a>",
            "in_reply_to_screen_name": "shanselman",
            "user": {
                "profile_sidebar_fill_color": "BABAB2",
                "profile_sidebar_border_color": "BABAB2",
                "name": "Seth Webster",
                "profile_background_tile": false,
                "location": "Tucson, Az",
                "profile_image_url": "http://a3.twimg.com/profile_images/1389477831/picture_1__normal",
                "created_at": "Mon Apr 28 19:27:07 +0000 2008",
                "follow_request_sent": false,
                "is_translator": false,
                "profile_link_color": "2891E2",
                "id_str": 14573883,
                "contributors_enabled": false,
                "favourites_count": 9,
                "default_profile": false,
                "url": "http://sethwebster.com",
                "id": 14573883,
                "profile_image_url_https": "https://si0.twimg.com/profile_images/1389477831/picture_1__normal",
                "utc_offset": "-25200",
                "profile_use_background_image": true,
                "listed_count": 25,
                "lang": "en",
                "profile_text_color": "47484D",
                "followers_count": 896,
                "protected": false,
                "profile_background_color": "FFFFFF",
                "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/257755044/x5558e73fec6d3a590f98d22491e3600.jpg",
                "description": "A musical vegan on a journey to make movies, music, software and a difference.  That is all.",
                "time_zone": "Arizona",
                "geo_enabled": true,
                "verified": false,
                "notifications": false,
                "profile_background_image_url": "http://a2.twimg.com/profile_background_images/257755044/x5558e73fec6d3a590f98d22491e3600.jpg",
                "statuses_count": 4958,
                "default_profile_image": false,
                "friends_count": 307,
                "screen_name": "sethwebster",
                "following": false,
                "show_all_inline_media": false
            },
            "place": null,
            "in_reply_to_status_id": 88333728409063420
        },
        "id_str": 88336989648191490,
        "entities": {
            "urls": [],
            "hashtags": [],
            "user_mentions": [{
                "name": "Seth Webster",
                "id_str": 14573883,
                "id": 14573883,
                "indices": [3, 15],
                "screen_name": "sethwebster"
            },
            {
                "name": "Scott Hanselman",
                "id_str": 5676102,
                "id": 5676102,
                "indices": [17, 28],
                "screen_name": "shanselman"
            }]
        },
        "in_reply_to_user_id_str": null,
        "contributors": null,
        "text": "RT @sethwebster: @shanselman I used to think you tweeted a lot.  Then I followed a bunch more people and now I barely see you.",
        "id": 88336989648191490,
        "retweet_count": 4,
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "source": "web",
        "in_reply_to_screen_name": null,
        "user": {
            "profile_sidebar_fill_color": "b8aa9c",
            "profile_sidebar_border_color": "b8aa9c",
            "name": "Scott Hanselman",
            "profile_background_tile": true,
            "location": "Portland, Oregon",
            "profile_image_url": "http://a2.twimg.com/profile_images/1425619283/image_normal.jpg",
            "created_at": "Tue May 01 05:55:26 +0000 2007",
            "follow_request_sent": false,
            "is_translator": false,
            "profile_link_color": "72412c",
            "id_str": 5676102,
            "contributors_enabled": false,
            "favourites_count": 2336,
            "default_profile": false,
            "url": "http://hanselman.com",
            "id": 5676102,
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1425619283/image_normal.jpg",
            "utc_offset": "-28800",
            "profile_use_background_image": true,
            "listed_count": 4063,
            "lang": "en",
            "profile_text_color": 696969,
            "followers_count": 38827,
            "protected": false,
            "profile_background_color": "d1cdc1",
            "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "description": "Tech, Diabetes, Parenting, Race, Linguistics, Fashion, Podcasting, Media, Culture, Code, Ratchet.",
            "time_zone": "Pacific Time (US & Canada)",
            "geo_enabled": true,
            "verified": false,
            "notifications": false,
            "profile_background_image_url": "http://a3.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "statuses_count": 44794,
            "default_profile_image": false,
            "friends_count": 2695,
            "screen_name": "shanselman",
            "following": true,
            "show_all_inline_media": true
        },
        "place": null,
        "in_reply_to_status_id": null
    },
    {
        "coordinates": null,
        "truncated": false,
        "created_at": "Tue Jul 05 19:52:05 +0000 2011",
        "favorited": false,
        "id_str": 88334354442485760,
        "entities": {
            "urls": [],
            "hashtags": [],
            "user_mentions": []
        },
        "in_reply_to_user_id_str": null,
        "contributors": null,
        "text": "On Twitter I'll unfollow you but on Google+ you'll be circumcised.",
        "id": 88334354442485760,
        "retweet_count": 35,
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "source": "web",
        "in_reply_to_screen_name": null,
        "user": {
            "profile_sidebar_fill_color": "b8aa9c",
            "profile_sidebar_border_color": "b8aa9c",
            "name": "Scott Hanselman",
            "profile_background_tile": true,
            "location": "Portland, Oregon",
            "profile_image_url": "http://a2.twimg.com/profile_images/1425619283/image_normal.jpg",
            "created_at": "Tue May 01 05:55:26 +0000 2007",
            "is_translator": false,
            "profile_link_color": "72412c",
            "id_str": 5676102,
            "follow_request_sent": false,
            "default_profile": false,
            "contributors_enabled": false,
            "favourites_count": 2335,
            "url": "http://hanselman.com",
            "id": 5676102,
            "utc_offset": "-28800",
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1425619283/image_normal.jpg",
            "profile_use_background_image": true,
            "listed_count": 4063,
            "lang": "en",
            "profile_text_color": 696969,
            "followers_count": 38836,
            "protected": false,
            "profile_background_color": "d1cdc1",
            "description": "Tech, Diabetes, Parenting, Race, Linguistics, Fashion, Podcasting, Media, Culture, Code, Ratchet.",
            "time_zone": "Pacific Time (US & Canada)",
            "geo_enabled": true,
            "verified": false,
            "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "notifications": false,
            "friends_count": 2695,
            "default_profile_image": false,
            "profile_background_image_url": "http://a3.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "statuses_count": 44776,
            "screen_name": "shanselman",
            "following": true,
            "show_all_inline_media": true
        },
        "place": null,
        "in_reply_to_status_id": null
    },
    {
        "coordinates": null,
        "truncated": false,
        "created_at": "Tue Jul 05 19:49:36 +0000 2011",
        "favorited": false,
        "id_str": 88333728409063420,
        "entities": {
            "urls": [],
            "hashtags": [{
                "text": "crisisaverted",
                "indices": [111, 125]
            }],
            "user_mentions": []
        },
        "in_reply_to_user_id_str": null,
        "contributors": null,
        "text": "Thinking of unfollowing someone for too many tweets? Here's a Twitter Pro Tip. Breathe, then SCROLL UP. *whew* #crisisaverted",
        "id": 88333728409063420,
        "retweet_count": 20,
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "source": "web",
        "in_reply_to_screen_name": null,
        "user": {
            "profile_sidebar_fill_color": "b8aa9c",
            "profile_sidebar_border_color": "b8aa9c",
            "name": "Scott Hanselman",
            "profile_background_tile": true,
            "location": "Portland, Oregon",
            "profile_image_url": "http://a2.twimg.com/profile_images/1425619283/image_normal.jpg",
            "created_at": "Tue May 01 05:55:26 +0000 2007",
            "profile_link_color": "72412c",
            "id_str": 5676102,
            "follow_request_sent": false,
            "is_translator": false,
            "default_profile": false,
            "favourites_count": 2336,
            "contributors_enabled": false,
            "url": "http://hanselman.com",
            "id": 5676102,
            "utc_offset": "-28800",
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1425619283/image_normal.jpg",
            "profile_use_background_image": true,
            "listed_count": 4063,
            "lang": "en",
            "profile_text_color": 696969,
            "followers_count": 38832,
            "protected": false,
            "geo_enabled": true,
            "profile_background_color": "d1cdc1",
            "description": "Tech, Diabetes, Parenting, Race, Linguistics, Fashion, Podcasting, Media, Culture, Code, Ratchet.",
            "time_zone": "Pacific Time (US & Canada)",
            "verified": false,
            "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "notifications": false,
            "default_profile_image": false,
            "friends_count": 2695,
            "profile_background_image_url": "http://a3.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "statuses_count": 44794,
            "screen_name": "shanselman",
            "show_all_inline_media": true,
            "following": true
        },
        "place": null,
        "in_reply_to_status_id": null
    },
    {
        "coordinates": null,
        "truncated": false,
        "created_at": "Tue Jul 05 19:48:28 +0000 2011",
        "favorited": false,
        "retweeted_status": {
            "coordinates": null,
            "truncated": false,
            "created_at": "Tue Jul 05 19:47:43 +0000 2011",
            "favorited": false,
            "id_str": 88333253571903490,
            "entities": {
                "urls": [],
                "hashtags": [],
                "user_mentions": [{
                    "name": "Scott Hanselman",
                    "id_str": 5676102,
                    "id": 5676102,
                    "indices": [16, 27],
                    "screen_name": "shanselman"
                }]
            },
            "in_reply_to_user_id_str": null,
            "contributors": null,
            "text": "Just unfollowed @shanselman! Too much fluff .. sorry dude!",
            "id": 88333253571903490,
            "retweet_count": 4,
            "in_reply_to_status_id_str": null,
            "geo": null,
            "retweeted": false,
            "in_reply_to_user_id": null,
            "source": "<a href=\"http://www.tweetdeck.com\" rel=\"nofollow\">TweetDeck</a>",
            "in_reply_to_screen_name": null,
            "user": {
                "profile_sidebar_fill_color": 252429,
                "profile_sidebar_border_color": "181A1E",
                "name": "azamsharp",
                "profile_background_tile": false,
                "location": "Houston, TX",
                "profile_image_url": "http://a0.twimg.com/profile_images/1084387884/8cbc2956-f164-4eb4-820c-203dbbe086c3_normal.png",
                "created_at": "Fri Dec 07 21:21:23 +0000 2007",
                "follow_request_sent": false,
                "is_translator": false,
                "profile_link_color": "2FC2EF",
                "id_str": 10950092,
                "favourites_count": 1,
                "contributors_enabled": false,
                "default_profile": false,
                "url": "http://www.highoncoding.com",
                "id": 10950092,
                "utc_offset": "-25200",
                "profile_image_url_https": "https://si0.twimg.com/profile_images/1084387884/8cbc2956-f164-4eb4-820c-203dbbe086c3_normal.png",
                "profile_use_background_image": true,
                "listed_count": 79,
                "lang": "en",
                "profile_text_color": 666666,
                "followers_count": 811,
                "protected": false,
                "profile_background_color": "1A1B1F",
                "description": null,
                "time_zone": "Mountain Time (US & Canada)",
                "verified": false,
                "geo_enabled": false,
                "profile_background_image_url_https": "https://si0.twimg.com/images/themes/theme9/bg.gif",
                "notifications": false,
                "friends_count": 109,
                "profile_background_image_url": "http://a1.twimg.com/images/themes/theme9/bg.gif",
                "default_profile_image": false,
                "statuses_count": 6446,
                "screen_name": "azamsharp",
                "following": false,
                "show_all_inline_media": false
            },
            "place": null,
            "in_reply_to_status_id": null
        },
        "id_str": 88333441891971070,
        "entities": {
            "urls": [],
            "hashtags": [],
            "user_mentions": [{
                "name": "azamsharp",
                "id_str": 10950092,
                "id": 10950092,
                "indices": [3, 13],
                "screen_name": "azamsharp"
            },
            {
                "name": "Scott Hanselman",
                "id_str": 5676102,
                "id": 5676102,
                "indices": [31, 42],
                "screen_name": "shanselman"
            }]
        },
        "in_reply_to_user_id_str": null,
        "contributors": null,
        "text": "RT @azamsharp: Just unfollowed @shanselman! Too much fluff .. sorry dude!",
        "id": 88333441891971070,
        "retweet_count": 4,
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "source": "web",
        "in_reply_to_screen_name": null,
        "user": {
            "profile_sidebar_fill_color": "b8aa9c",
            "profile_sidebar_border_color": "b8aa9c",
            "name": "Scott Hanselman",
            "profile_background_tile": true,
            "location": "Portland, Oregon",
            "profile_image_url": "http://a2.twimg.com/profile_images/1425619283/image_normal.jpg",
            "created_at": "Tue May 01 05:55:26 +0000 2007",
            "follow_request_sent": false,
            "is_translator": false,
            "profile_link_color": "72412c",
            "id_str": 5676102,
            "favourites_count": 2336,
            "contributors_enabled": false,
            "default_profile": false,
            "url": "http://hanselman.com",
            "id": 5676102,
            "utc_offset": "-28800",
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1425619283/image_normal.jpg",
            "profile_use_background_image": true,
            "listed_count": 4063,
            "lang": "en",
            "profile_text_color": 696969,
            "followers_count": 38832,
            "protected": false,
            "profile_background_color": "d1cdc1",
            "description": "Tech, Diabetes, Parenting, Race, Linguistics, Fashion, Podcasting, Media, Culture, Code, Ratchet.",
            "time_zone": "Pacific Time (US & Canada)",
            "verified": false,
            "geo_enabled": true,
            "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "notifications": false,
            "friends_count": 2695,
            "profile_background_image_url": "http://a3.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "default_profile_image": false,
            "statuses_count": 44794,
            "screen_name": "shanselman",
            "following": true,
            "show_all_inline_media": true
        },
        "place": null,
        "in_reply_to_status_id": null
    },
    {
        "coordinates": null,
        "truncated": false,
        "created_at": "Tue Jul 05 19:46:28 +0000 2011",
        "favorited": false,
        "id_str": 88332938990727170,
        "entities": {
            "urls": [],
            "hashtags": [],
            "user_mentions": [{
                "name": "afrobella",
                "id_str": 16279527,
                "id": 16279527,
                "indices": [7, 17],
                "screen_name": "afrobella"
            }]
        },
        "in_reply_to_user_id_str": null,
        "contributors": null,
        "text": "LOL RT @afrobella Here's a sentence I never thought I'd say in my life.... I can't wait to hear what Nancy Grace has to say about this.",
        "id": 88332938990727170,
        "retweet_count": 13,
        "in_reply_to_status_id_str": null,
        "geo": null,
        "retweeted": false,
        "in_reply_to_user_id": null,
        "source": "web",
        "in_reply_to_screen_name": null,
        "user": {
            "profile_sidebar_fill_color": "b8aa9c",
            "profile_sidebar_border_color": "b8aa9c",
            "name": "Scott Hanselman",
            "profile_background_tile": true,
            "location": "Portland, Oregon",
            "profile_image_url": "http://a2.twimg.com/profile_images/1425619283/image_normal.jpg",
            "created_at": "Tue May 01 05:55:26 +0000 2007",
            "follow_request_sent": false,
            "is_translator": false,
            "profile_link_color": "72412c",
            "id_str": 5676102,
            "contributors_enabled": false,
            "default_profile": false,
            "favourites_count": 2328,
            "url": "http://hanselman.com",
            "id": 5676102,
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1425619283/image_normal.jpg",
            "utc_offset": "-28800",
            "profile_use_background_image": true,
            "listed_count": 4063,
            "lang": "en",
            "profile_text_color": 696969,
            "followers_count": 38838,
            "protected": false,
            "profile_background_color": "d1cdc1",
            "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "description": "Tech, Diabetes, Parenting, Race, Linguistics, Fashion, Podcasting, Media, Culture, Code, Ratchet.",
            "time_zone": "Pacific Time (US & Canada)",
            "verified": false,
            "geo_enabled": true,
            "notifications": false,
            "profile_background_image_url": "http://a3.twimg.com/profile_background_images/157325454/twilk_background_4ca8e4832a970.jpg",
            "statuses_count": 44752,
            "default_profile_image": false,
            "friends_count": 2694,
            "screen_name": "shanselman",
            "following": true,
            "show_all_inline_media": true
        },
        "place": null,
        "in_reply_to_status_id": null
    }]
};