//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DowJones.Dash.Components.TopReferrer
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 12/11/2012 11:22 AM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Dash.Components.TopReferrer.TopReferrer.js", DependsOn=new string[] {
            "highcharts-more"}, ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Dash.Components.TopReferrer.TopPagesComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Dash.Components.TopReferrer.ClientTemplates.container.html", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="container", DeclaringType=typeof(DowJones.Dash.Components.TopReferrer.TopPagesComponent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.27108")]
    public class TopPagesComponent : DowJones.Dash.Components.DashboardComponent<DowJones.Dash.Components.Models.PageTimings.PageTimingsModel>
    {
#line hidden

        public TopPagesComponent()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_TopReferrer";
            }
        }
        public override void ExecuteTemplate()
        {






   CssClass = "dj_TopReferrer"; 


        }
    }
}
