//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.VideoPlayer.js.scrollable.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.VideoPlayer.js.VideoPlayer.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.VideoPlayer.js.flowplayer-combined.js", "text/javascript")]

namespace DowJones.Web.Mvc.UI.Components.VideoPlayer
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 06/29/2012 01:49 PM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.VideoPlayer.js.scrollable.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.VideoPlayer.VideoPlayerComponent))]
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.VideoPlayer.js.VideoPlayer.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.VideoPlayer.VideoPlayerComponent))]
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.VideoPlayer.js.flowplayer-combined.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.VideoPlayer.VideoPlayerComponent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.22175")]
    public class VideoPlayerComponent : DowJones.Web.Mvc.UI.ViewComponentBase<VideoPlayerModel>
    {
#line hidden

        public VideoPlayerComponent()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_VideoPlayerControl";
            }
        }
        public override void ExecuteTemplate()
        {







   
    CssClass = "dj_VideoPlayerControl";


WriteLiteral(@"
<div class=""video-player""></div>
<div class=""playlist-container"" style=""display:none;"">
    <div class=""playlist-wrap"" style=""display:none;""> 
	    <a class=""prev""></a> 
	    <div class=""playlist-items""> 
		    <div class=""entries""></div> 
	    </div> 
	    <a class=""next""></a> 
        <br clear=""all"" />  
    </div> 
    <div class=""clearFix playlist-nav"">
        <table cellpadding=""0"" cellspacing=""0"" width=""100%"">
            <tr>
                <td><a class=""prev-btn"" href=""javascript:void(0);"">&laquo; ");


                                                                      Write(Html.DJ().Token("prev"));

WriteLiteral("</a></td>\r\n                <td align=\"center\"><a class=\"playlist-btn\" href=\"javas" +
"cript:void(0);\">");


                                                                                 Write(Html.DJ().Token("playlist"));

WriteLiteral("</a></td>\r\n                <td align=\"right\"><a class=\"next-btn\" href=\"javascript" +
":void(0);\">");


                                                                            Write(Html.DJ().Token("next"));

WriteLiteral(" &raquo;</a></td>\r\n            </tr>\r\n        </table>\r\n    </div>\r\n</div>\r\n");


        }
    }
}
