//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Canvas.Editors.CompanyOverview.CompanyOverviewModuleEditor.js" +
    "", "text/javascript")]

namespace DowJones.Web.Mvc.UI.Canvas.Editors.CompanyOverview
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.UI.Canvas;
    using DowJones.Web.Mvc.UI.Canvas.Editors.CompanyOverview;
    using DowJones.Web.Mvc.UI.Components.AutoSuggest;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 05/04/2011 11:24 AM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Canvas.Editors.CompanyOverview.CompanyOverviewModuleEditor.js" +
        "", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Canvas.Editors.CompanyOverview.CompanyOverviewModuleEditor))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "0.9.3.26911")]
    public class CompanyOverviewModuleEditor : AbstractCanvasModuleEditor<CompanyOverviewModuleEditor>
    {
#line hidden

        public CompanyOverviewModuleEditor()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_CompanyOverviewModuleEditor";
            }
        }
        public override void ExecuteTemplate()
        {







        
    CssClass = "dj_Editor dj_CompanyOverviewModuleEditor";
    Html.DJ().AutoSuggest();


WriteLiteral("<div class=\"dj_edit-col\">\r\n    <div class=\"dj_edit-input-wrap\">\r\n        <label f" +
"or=\"\" class=\"dj_edit-label\">\r\n            ");


       Write(Html.DJ().Token("moduleName"));

WriteLiteral("</label>\r\n        <div class=\"dj_text-element-wrapper\">\r\n            <input type=" +
"\"text\" id=\"txtModuleName\" maxlength=\"25\" /></div> \r\n    </div>\r\n    <div class=\"" +
"dj_edit-input-wrap\">\r\n        <label for=\"\" class=\"dj_edit-label\">\r\n            " +
"");


       Write(Html.DJ().Token("description"));

WriteLiteral("</label>\r\n        <span class=\"dj_max-char-note\">(");


                                   Write(Html.DJ().Token("max250Chars"));

WriteLiteral(@")</span>
        <div class=""dj_text-element-wrapper"">
            <textarea id=""txtDescription""></textarea></div>
    </div>
</div>
<div class=""dj_edit-col two-thirds"">
    <div class=""dj_edit-input-wrap"">
        <label for="""" class=""dj_edit-label"">
            ");


       Write(Html.DJ().Token("companyLabel"));

WriteLiteral(@"</label>
        <div class=""dj_text-element-wrapper add-company-wrap approved"">
            <input type=""text"" class=""ac_input"" id=""txtCompanyEditSearch"" />
        </div>
        <div class=""txtCompany"">
            <ul class=""dj_edit-lists ui-sortable"" id=""dj_company_list"" style=""""></ul>
        </div>
        
    </div>
</div>
");


        }
    }
}
