//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.VideoPlayer.js.scrollable.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.VideoPlayer.js.VideoPlayer.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.VideoPlayer.js.flowplayer-combined.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.VideoPlayer.ClientTemplates.Success.htm", "text/html")]

namespace DowJones.Web.Mvc.UI.Components.VideoPlayer
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 07/20/2012 10:23 AM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.VideoPlayer.js.scrollable.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.VideoPlayer.VideoPlayerComponent))]
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.VideoPlayer.js.VideoPlayer.js", DependsOn=new string[] {
            "scrollable","flow-player-combined"}, ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.VideoPlayer.VideoPlayerComponent))]
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.VideoPlayer.js.flowplayer-combined.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.VideoPlayer.VideoPlayerComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.VideoPlayer.ClientTemplates.Success.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="success", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.VideoPlayer.VideoPlayerComponent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.27108")]
    public class VideoPlayerComponent : DowJones.Web.Mvc.UI.ViewComponentBase<VideoPlayerModel>
    {
#line hidden

        public VideoPlayerComponent()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_VideoPlayer";
            }
        }
        public override void ExecuteTemplate()
        {








   
    CssClass = "dj_VideoPlayer";


WriteLiteral("\r\n");


        }
    }
}
