//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.RelatedConcepts.RelatedConcepts.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.RelatedConcepts.ClientTemplates.Success.htm", "text/html")]

namespace DowJones.Web.Mvc.UI.Components.RelatedConcepts
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 07/27/2012 04:27 PM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.RelatedConcepts.RelatedConcepts.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.RelatedConcepts.RelatedConceptsComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.RelatedConcepts.ClientTemplates.Success.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="success", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.RelatedConcepts.RelatedConceptsComponent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.27108")]
    public class RelatedConceptsComponent : DowJones.Web.Mvc.UI.ViewComponentBase<RelatedConceptsComponentModel>
    {
#line hidden

        public RelatedConceptsComponent()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_RelatedConceptsComponent";
            }
        }
        public override void ExecuteTemplate()
        {




WriteLiteral("\r\n\r\n");


   
    CssClass = "dj_RelatedConceptsComponent"; 


WriteLiteral("\r\n");


        }
    }
}
