//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.PortalHeadlineList.ClientTemplates.Error.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.PortalHeadlineList.ClientTemplates.Success.htm", "text/html", PerformSubstitution=true)]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.PortalHeadlineList.ClientTemplates.NoData.htm", "text/html", PerformSubstitution=true)]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.PortalHeadlineList.ClientTemplates.AddNewContent.h" +
    "tm", "text/html", PerformSubstitution=true)]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.PortalHeadlineList.ClientTemplates.TimeLine.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.PortalHeadlineList.PortalHeadlineList.js", "text/javascript", PerformSubstitution=true)]

namespace DowJones.Web.Mvc.UI.Components.PortalHeadlineList
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 03/26/2011 04:23 PM
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.PortalHeadlineList.ClientTemplates.Error.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="error", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.PortalHeadlineList.PortalHeadlineListControl))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.PortalHeadlineList.ClientTemplates.Success.htm", PerformSubstitution=true, ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="success", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.PortalHeadlineList.PortalHeadlineListControl))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.PortalHeadlineList.ClientTemplates.NoData.htm", PerformSubstitution=true, ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="noData", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.PortalHeadlineList.PortalHeadlineListControl))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.PortalHeadlineList.ClientTemplates.AddNewContent.h" +
        "tm", PerformSubstitution=true, ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="addNewContent", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.PortalHeadlineList.PortalHeadlineListControl))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.PortalHeadlineList.ClientTemplates.TimeLine.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="timeline", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.PortalHeadlineList.PortalHeadlineListControl))]
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.PortalHeadlineList.PortalHeadlineList.js", PerformSubstitution=true, ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.PortalHeadlineList.PortalHeadlineListControl))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "0.0.0.30158")]
    public class PortalHeadlineListControl : DowJones.Web.Mvc.UI.ViewComponentBase<DowJones.Web.Mvc.UI.Components.Models.PortalHeadlineListModel>
    {
#line hidden

        public PortalHeadlineListControl()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_PortalHeadlineList";
            }
        }
        public override void ExecuteTemplate()
        {









   
    CssClass = "dj_headlineListContainer article-group";
    Html.DJ().ScriptRegistry().WithUnderscoreJS();



        }
    }
}
