//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DowJones.Web.Mvc.UI.Canvas.Modules.ScriptModule.Editor
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 08/27/2012 03:19 PM
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.27108")]
    public class ScriptModuleEditorComponent : AbstractCanvasModuleEditor<Modules.ScriptModule.Editor.ScriptModuleEditor>
    {
#line hidden

        public ScriptModuleEditorComponent()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_CanvasModuleEditor";
            }
        }
        public override void ExecuteTemplate()
        {



   CssClass += " dj_ScriptModuleEditor"; 

WriteLiteral("\r\n<input type=\"hidden\" name=\"moduleId\" value=\"");


                                       Write(Model.ModuleId);

WriteLiteral("\"/>\r\n<input type=\"hidden\" name=\"templateId\" value=\"");


                                         Write(Model.TemplateId);

WriteLiteral("\"/>\r\n\r\n<fieldset>\r\n    <p>\r\n        <label>");


          Write(DJ.Token("title"));

WriteLiteral("</label>\r\n        <textarea name=\"title\" class=\"title\">");


                                        Write(Model.Title);

WriteLiteral("</textarea>\r\n    </p>\r\n    \r\n");


       var i = 0; 


     foreach(var option in Model.Options)
    {

WriteLiteral("        <p class=\"option\">\r\n            <label>");


              Write(option.DisplayName);

WriteLiteral("</label>\r\n            <input type=\"hidden\" name=\"options[");


                                           Write(i);

WriteLiteral("].Name\" value=\"");


                                                             Write(option.Name);

WriteLiteral("\" />\r\n            <textarea name=\"options[");


                                Write(i);

WriteLiteral("].Value\">");


                                            Write(option.DefaultValue);

WriteLiteral("</textarea>\r\n        </p>\r\n");


                        
        i++;
    }

WriteLiteral("</fieldset>\r\n");


        }
    }
}
