//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.HeadlineList.HeadlineList.js", "text/javascript")]

namespace DowJones.Web.Mvc.UI.Components.HeadlineList
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Extensions;
    using DowJones.Web.Mvc.Extensions;
    using DowJones.Web.Mvc.UI.Components.HeadlineList;
    using System.Collections.ObjectModel;
    using DowJones.Web.Mvc.UI.Components.Common.Types;
    
    // Last Generated Timestamp: 02/03/2012 02:42 PM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.HeadlineList.HeadlineList.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.HeadlineList.HeadlineListControl))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "0.0.0.30158")]
    public class HeadlineListControl : DowJones.Web.Mvc.UI.ViewComponentBase<DowJones.Web.Mvc.UI.Components.HeadlineList.HeadlineListModel>
    {
#line hidden

        public HeadlineListControl()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_HeadlineList";
            }
        }
        public override void ExecuteTemplate()
        {









   CssClass = "dj_HeadlineListControl"; 

WriteLiteral("<ul class=\"dj_HeadlineList items\">\r\n");


     if (Model != null)
    {
        // need the index for displaying hybrid snippets
        int i = 0;
        foreach (var headline in Model.Headlines)
        {
            bool showPressClip = (Model.ShowPressClip && !string.IsNullOrEmpty(headline.HeadlineInfo.subType) && headline.HeadlineInfo.subType.ToLower() == "nlapressclip");

WriteLiteral("        <li class=\"headline-box item headlineItem\" data-headlineInfo=\"");


                                                                 Write(headline.HeadlineInfo.ToJson().EscapeForHtml());

WriteLiteral("\">\r\n");


             if (Model.ShowCheckboxes)
            {

WriteLiteral("                <div class=\"select ");


                               Write(Model.ShowDuplicates == ShowDuplicates.On && headline.HasDuplicates ? " duplicate" : "");

WriteLiteral(" dj_selectActions\">\r\n                    <input class=\"chk-headline dj_ChkHeadlin" +
"e\" type=\"checkbox\" autocomplete=\"off\" />\r\n                </div>\r\n");


                
            }


             if (Model.ShowContentType)
            {

WriteLiteral("                <div class=\"dj_contentType ");


                                      Write(headline.HeadlineInfo.contentSubCategory);

WriteLiteral("\">\r\n                    &nbsp;</div>\r\n");


            }


             if (Model.IsThumbnailVisible(i, headline))
            {

WriteLiteral("                <div class=\"articleImage\">\r\n                    <img src=\"");


                         Write(headline.ThumbnailUrl);

WriteLiteral("\" alt=\"");


                                                      Write(headline.TruncatedTitle);

WriteLiteral("\" />\r\n                </div>\r\n");


            }

WriteLiteral("            <a class=\"title\" href=\"javascript:void(0)\" rel=\"");


                                                       Write(headline.ExternalUrl);

WriteLiteral("\" title=\"");


                                                                                     Write(Model.GetHoverSnippet(headline.Snippet, i));

WriteLiteral("\" >");


                                                                                                                                   Write(headline.Title);

WriteLiteral("</a>\r\n");


             if (Model.ShowPressClip && headline.IsPressClipArticle)
            {

WriteLiteral("                <span class=\"dj_badge-pressclips\">");


                                             Write(Html.DJ().Token("pressClipping"));

WriteLiteral("</span>        \r\n");


            }

WriteLiteral("            <div class=\"meta\">\r\n                <span class=\"value source drop-do" +
"wn-button ");


                                                       Write(headline.IsLocked ? "locked" : "unlocked");

WriteLiteral("\" data-source=\"");


                                                                                                                 Write(headline.SourceCode);

WriteLiteral("\">");


                                                                                                                                       Write(headline.Source);

WriteLiteral("</span>\r\n");


                 if (Model.ShowByLine && headline.Authors != null && headline.Authors.Count() > 0)
                {

WriteLiteral("                    <span class=\"dj_article-by\">");


                                           Write(Html.DJ().Token("by"));

WriteLiteral("</span>\r\n");


                    foreach (var author in headline.Authors)
                    {

WriteLiteral("                    <span class=\"value author drop-down-button\" data-author=");


                                                                       Write(author.Code);

WriteLiteral(">");


                                                                                    Write(author.Name);

WriteLiteral("</span>   \r\n");


                    }
                }

WriteLiteral("                <span class=\"date-stamp\">");


                                    Write(string.Join(", ", new[] { headline.PublicationDateDisplay, headline.WordCount, headline.Language }.Where(s => !string.IsNullOrWhiteSpace(s))));

WriteLiteral("</span>\r\n            </div>\r\n");


             if (Model.DisplaySnippets == SnippetDisplayType.Inline ||
                (i == 0 && Model.DisplaySnippets == SnippetDisplayType.Hybrid))
            {

WriteLiteral("                <p class=\"snippet\">\r\n                    ");


               Write(headline.Snippet);

WriteLiteral("\r\n                </p>\r\n");


            }


             if (Model.ShowPostProcessing)
            {

WriteLiteral("                <div class=\"actions\">\r\n                    <ol class=\"options\">\r\n" +
"");


                         foreach (var item in Model.PostProcessingOptions)
                        {

WriteLiteral("                            <li><span title=\"");


                                        Write(Html.DJ().Token(item.ToString().ToLower() + "ArticlesTitle"));

WriteLiteral("\" \r\n                            class=\"dj_icon dj_icon-inactive-");


                                                       Write(item.ToString().ToLower());

WriteLiteral(" dj_icon-");


                                                                                          Write(item.ToString().ToLower());

WriteLiteral("\">\r\n                            </span></li>\r\n");


            
                        }

WriteLiteral("                    </ol>\r\n                </div>\r\n");


            }

WriteLiteral("            <!-- end: actions -->\r\n");


             if (Model.ShowDuplicates == ShowDuplicates.On && headline.HasDuplicates)
            {

WriteLiteral("                <div class=\"duplicateWrapper clearfix\">\r\n                    <p><" +
"span class=\"dj_icon dj_icon-blk-filter-r-arrow\"></span><strong>Duplicates</stron" +
"g>\r\n                        (");


                    Write(headline.DuplicateHeadlines.Count());

WriteLiteral(")</p>\r\n                    <ul class=\"hide\">\r\n");


                         foreach (var dup in headline.DuplicateHeadlines)
                        {
                            showPressClip = (Model.ShowPressClip && !string.IsNullOrEmpty(dup.HeadlineInfo.subType) && dup.HeadlineInfo.subType.ToLower() == "nlapressclip");

WriteLiteral("                            <li class=\"headlineItem\" data-headlineInfo=\"");


                                                                   Write(dup.HeadlineInfo.ToJson().EscapeForHtml());

WriteLiteral("\">\r\n");


                                 if (Model.ShowCheckboxes)
                                {

WriteLiteral("                                    <input class=\"chk-headline dj_dupChkHeadline\"" +
" type=\"checkbox\" value=\"");


                                                                                                    Write(dup.AccessionNumber);

WriteLiteral("\" autocomplete=\"off\" />\r\n");


                                }

WriteLiteral("                                <a class=\"title\" href=\"#\" title=\"");


                                                            Write(headline.Snippet.EscapeForHtml());

WriteLiteral("\">");


                                                                                               Write(dup.Title);

WriteLiteral("</a>\r\n");


                                 if (Model.ShowPressClip && dup.IsPressClipArticle)
                                {

WriteLiteral("                                    <span class=\"dj_badge-pressclips\">");


                                                                 Write(Html.DJ().Token("pressClipping"));

WriteLiteral("</span>        \r\n");


                                }

WriteLiteral("                                <div class=\"meta\">\r\n                             " +
"       <span class=\"value source drop-down-button\" data-source=\"");


                                                                                        Write(dup.SourceCode);

WriteLiteral("\">");


                                                                                                         Write(dup.Source);

WriteLiteral("</span>\r\n");


                                     if (Model.ShowByLine && dup.Authors != null && dup.Authors.Count() > 0)
                                    {

WriteLiteral("                                        <span class=\"dj_article-by\">");


                                                               Write(Html.DJ().Token("by"));

WriteLiteral("</span>\r\n");


                                        foreach (var author in dup.Authors)
                                        {

WriteLiteral("                                        <span class=\"value author drop-down-butto" +
"n\" data-author=");


                                                                                           Write(author.Code);

WriteLiteral(">");


                                                                                                        Write(author.Name);

WriteLiteral("</span>   \r\n");


                                        }
                                    }

WriteLiteral("                                    <span class=\"date-stamp\">");


                                                        Write(dup.PublicationDateDisplay);

WriteLiteral(", ");


                                                                                     Write(dup.WordCount);

WriteLiteral(", ");


                                                                                                     Write(dup.Language);

WriteLiteral("</span>\r\n                                </div>\r\n                            </li" +
">\r\n");


                        }

WriteLiteral("                    </ul>\r\n                </div>\r\n");


            }


             if (Model.ShowAccessionNo)
            {

WriteLiteral("                <div class=\"accessionNo\">");


                                    Write(DJ.Token("document"));

WriteLiteral(" ");


                                                          Write(headline.AccessionNumber);

WriteLiteral("</div>\r\n");


            }

WriteLiteral("        </li>\r\n");


            i++;
        }
    }
    else
    {

WriteLiteral("        <li><span class=\"dj_noResults\">");


                                  Write(DJ.Token("noResults"));

WriteLiteral("</span></li>\r\n");


    }

WriteLiteral("</ul>\r\n");


        }
    }
}
