using System.Web.UI;
using DowJones.Web;

[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.small.delicious.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.small.digg.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.small.facebook.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.small.furl.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.small.google.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.small.linkedin.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.small.myspace.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.small.newsvine.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.small.reddit.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.small.stumbleupon.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.small.technorati.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.small.twitter.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.small.yahoo.png", KnownMimeTypes.PngImage)]

[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.large.delicious.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.large.digg.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.large.facebook.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.large.furl.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.large.google.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.large.linkedin.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.large.myspace.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.large.newsvine.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.large.reddit.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.large.stumbleupon.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.large.technorati.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.large.twitter.png", KnownMimeTypes.PngImage)]
[assembly: WebResource("DowJones.Web.Mvc.UI.Components.SocialButtons.large.yahoo.png", KnownMimeTypes.PngImage)]