//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.CompanySparkline.CompanySparkline.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.CompanySparkline.ClientTemplates.PillContents.htm", "text/html")]

namespace DowJones.Web.Mvc.UI.Components.CompanySparkline
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 09/21/2011 01:47 PM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.CompanySparkline.CompanySparkline.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.CompanySparkline.CompanySparkline))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.CompanySparkline.ClientTemplates.PillContents.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="pillcontents", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.CompanySparkline.CompanySparkline))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "0.0.0.30158")]
    public class CompanySparkline : DowJones.Web.Mvc.UI.ViewComponentBase<DowJones.Web.Mvc.UI.Components.Models.CompanySparkline.CompanySparklineModel>
    {
#line hidden

        public CompanySparkline()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_CompanySparkline";
            }
        }
        public override void ExecuteTemplate()
        {







   
    
    CssClass = "dj_CompanySparkline dj_sparkline";
    Html.DJ().ScriptRegistry().WithHighCharts();
    
 

        }
    }
}
