//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.SimpleAlert.ClientTemplates.Layout.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.SimpleAlert.ClientTemplates.Options.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.SimpleAlert.ClientTemplates.NewsFilter.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.SimpleAlert.ClientTemplates.NewsFilterEx.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.SimpleAlert.SimpleAlert.js", "text/javascript")]

namespace DowJones.Web.Mvc.UI.Components.SimpleAlert
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 12/14/2012 01:23 PM
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.SimpleAlert.ClientTemplates.Layout.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="layout", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.SimpleAlert.SimpleAlertComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.SimpleAlert.ClientTemplates.Options.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="options", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.SimpleAlert.SimpleAlertComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.SimpleAlert.ClientTemplates.NewsFilter.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="newsFilter", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.SimpleAlert.SimpleAlertComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.SimpleAlert.ClientTemplates.NewsFilterEx.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="newsFilterEx", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.SimpleAlert.SimpleAlertComponent))]
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.SimpleAlert.SimpleAlert.js", DependsOn=new string[] {
            "newsfilterPillMenu-plugin",
            ""}, ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.SimpleAlert.SimpleAlertComponent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.27108")]
    public class SimpleAlertComponent : DowJones.Web.Mvc.UI.ViewComponentBase<SimpleAlertModel>
    {
#line hidden

        public SimpleAlertComponent()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_SimpleAlert";
            }
        }
        public override void ExecuteTemplate()
        {









   
    CssClass = "dj_SimpleAlert";
    Html.DJ().ScriptRegistry();


        }
    }
}
