//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.TaxonomySearchBrowse.ClientTemplates.main.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.TaxonomySearchBrowse.ClientTemplates.searchList.ht" +
    "m", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.TaxonomySearchBrowse.ClientTemplates.listItemOptio" +
    "ns.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.TaxonomySearchBrowse.ClientTemplates.browseList.ht" +
    "m", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.TaxonomySearchBrowse.ClientTemplates.djIICode.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.TaxonomySearchBrowse.TaxonomySearchBrowse.js", "text/javascript")]

namespace DowJones.Web.Mvc.UI.Components.TaxonomySearchBrowse
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 06/29/2012 01:36 PM
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.TaxonomySearchBrowse.ClientTemplates.main.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="main", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.TaxonomySearchBrowse.TaxonomySearchBrowseComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.TaxonomySearchBrowse.ClientTemplates.searchList.ht" +
        "m", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="searchList", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.TaxonomySearchBrowse.TaxonomySearchBrowseComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.TaxonomySearchBrowse.ClientTemplates.listItemOptio" +
        "ns.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="listItemOptions", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.TaxonomySearchBrowse.TaxonomySearchBrowseComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.TaxonomySearchBrowse.ClientTemplates.browseList.ht" +
        "m", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="browseList", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.TaxonomySearchBrowse.TaxonomySearchBrowseComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.TaxonomySearchBrowse.ClientTemplates.djIICode.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="djIICode", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.TaxonomySearchBrowse.TaxonomySearchBrowseComponent))]
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.TaxonomySearchBrowse.TaxonomySearchBrowse.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.TaxonomySearchBrowse.TaxonomySearchBrowseComponent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.22175")]
    public class TaxonomySearchBrowseComponent : DowJones.Web.Mvc.UI.ViewComponentBase<TaxonomySearchBrowseModel>
    {
#line hidden

        public TaxonomySearchBrowseComponent()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_TaxonomySearchBrowse";
            }
        }
        public override void ExecuteTemplate()
        {










   
    CssClass = "dj_TaxonomySearchBrowse";



        }
    }
}
