//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DowJones.Web.Mvc.UI.Components.Diagnostics
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 05/09/2012 01:31 PM
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.22175")]
    public class ValidateClientUIComponent : DowJones.Web.Mvc.UI.ViewComponentBase<ValidateClientUI>
    {
#line hidden

        public ValidateClientUIComponent()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return null;
            }
        }
        public override void ExecuteTemplate()
        {

WriteLiteral("\r\n<style>\r\n    .testing { background-color: orange; font-style: italic; }\r\n    .p" +
"assed { background-color: greenyellow; }\r\n    .timeout, .failed, .error {\r\n     " +
"   background-color: red; \r\n        font-weight: bold;\r\n        font-size: 120%;" +
"\r\n        color: #fff;\r\n    }\r\n    \r\n    #validation-steps li,\r\n    #failures li" +
" {\r\n        padding: 5px;\r\n    }\r\n</style>\r\n\r\n<div class=\"loading\">Validating th" +
"at everything was installed and configured properly...</div>\r\n<ol id=\"validation" +
"-steps\"></ol>\r\n<ol id=\"failures\" class=\"failed\"></ol>\r\n\r\n<script type=\"text/java" +
"script\">\r\n    if (DJ && DJ.config) { DJ.config.debug = true; }\r\n\r\n    var TIMEOU" +
"T = 5000;\r\n    var container, tests, failures, loadedComponentNames = [];\r\n\r\n   " +
" function failure(message) {\r\n        var el = document.createElement(\"li\");\r\n  " +
"      el.innerText = message;\r\n        failures.appendChild(el);\r\n    }\r\n\r\n    f" +
"unction success(message) {\r\n        var el = document.createElement(\"li\");\r\n    " +
"    el.innerText = message;\r\n        el.className = \'passed\';\r\n        container" +
".appendChild(el);\r\n    }\r\n\r\n    function validate(description, test) {\r\n        " +
"var _result;\r\n\r\n        var statusEl = document.createElement(\"li\");\r\n        st" +
"atusEl.innerText = description;\r\n        container.appendChild(statusEl);\r\n\r\n   " +
"     var setStatus = function (val, text) {\r\n            statusEl.className = va" +
"l;\r\n\r\n            if (text)\r\n                console.log(description, \": \", text" +
");\r\n        };\r\n\r\n        var evalResult = function (result) {\r\n            _res" +
"ult = result;\r\n\r\n            if (_result === \'timeout\') {\r\n                setSt" +
"atus(\"timeout\");\r\n            } else if (_result) {\r\n                setStatus(\"" +
"passed\");\r\n            } else {\r\n                setStatus(\"failed\");\r\n         " +
"   }\r\n        };\r\n\r\n        var timeout = function () {\r\n            if (_result" +
") return;\r\n            evalResult(\'timeout\');\r\n        };\r\n\r\n        setStatus(\"" +
"testing\");\r\n\r\n        try {\r\n            setTimeout(timeout, TIMEOUT);\r\n        " +
"    test(evalResult);\r\n        } catch (e) {\r\n            setStatus(\"error\", e);" +
"\r\n        }\r\n    }\r\n\r\n    try {\r\n        container = document.getElementById(\"va" +
"lidation-steps\");\r\n        failures = document.getElementById(\"failures\");\r\n\r\n  " +
"      var log = DJ.$dj._log;\r\n        DJ.$dj._log = function(message) {\r\n       " +
"     if (( /Registered DJ.*/ ).test(message)) {\r\n                var component =" +
" ( /DJ.[^ ]*/ ).exec(message);\r\n                loadedComponentNames.push(compon" +
"ent);\r\n                success(\'Loaded \' + component);\r\n            }\r\n\r\n       " +
"     if (arguments[arguments.length - 1] == \"error\")\r\n                failure(ar" +
"guments[0]);\r\n\r\n            log.apply(arguments);\r\n        };\r\n\r\n        (functi" +
"on (require) {\r\n            var onError = require.onError;\r\n            require." +
"onError = function (err) {\r\n                var modules = err.requireModules.spl" +
"it(\' \');\r\n                for (var i = 0; i < modules.length; i++) {\r\n          " +
"          if(modules[i] && modules[i].length > 0)\r\n                        failu" +
"re(\'Failed to load \' + modules[i]);\r\n                }\r\n                onError(" +
"err);\r\n            };\r\n\r\n            var onScriptLoad = require.onScriptLoad;\r\n " +
"           require.onScriptLoad = function () {\r\n                try {\r\n        " +
"            onScriptLoad.apply(arguments);\r\n                } catch (err) {\r\n   " +
"                 DJ.$dj.error(err);\r\n                }\r\n            };\r\n        " +
"})(DJ.$dj.require);\r\n\r\n    } catch (e) {\r\n        failure(e);\r\n    }\r\n\r\n    wind" +
"ow.onload = function () {\r\n        container = document.getElementById(\"validati" +
"on-steps\");\r\n        failures = document.getElementById(\"failures\");\r\n\r\n        " +
"validate(\"DJ exists\", function (callback) {\r\n            callback(DJ !== undefin" +
"ed);\r\n        });\r\n\r\n\r\n        validate(\"DJ.config exists\", function (callback) " +
"{\r\n            callback(DJ.config !== undefined);\r\n        });\r\n\r\n        valida" +
"te(\"DJ.jQuery exists\", function (callback) {\r\n            callback(DJ.jQuery !==" +
" undefined);\r\n        });\r\n\r\n        validate(\"DJ.UI.Component exists\", function" +
" (callback) {\r\n            callback(DJ.UI.Component !== undefined);\r\n        });" +
"\r\n\r\n        validate(\"DJ.$dj.require exists\", function (callback) {\r\n           " +
" callback(DJ.$dj.require !== undefined);\r\n        });\r\n\r\n        validate(\"requi" +
"re(\'JSON\')\", function (callback) {\r\n            DJ.$dj.require([\'JSON\'], functio" +
"n (JSON) {\r\n                callback(JSON !== undefined);\r\n            });\r\n    " +
"    });\r\n\r\n        validate(\"Can create PortalHeadlineList\", function (callback)" +
" {\r\n            DJ.$dj.require([\'$\', \'$dj\', \'DowJones.Web.Mvc.UI.Components.Port" +
"alHeadlineList.PortalHeadlineList\'], function ($, $dj) {\r\n                callba" +
"ck($(\'<div>\').dj_PortalHeadlineList({}));\r\n            });\r\n        });\r\n\r\n");


          
            var scriptRegistry = DJ.ScriptRegistry();
    
            foreach (var component in Model.ViewComponentTypes.OrderBy(x => x.Name))
            {
                scriptRegistry.With(component);
            }
        

WriteLiteral("\r\n\r\n    };\r\n</script>");


        }
    }
}
