//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.Twitter.TwitterProfile.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.Twitter.ClientTemplates.profile.htm", "text/html")]

namespace DowJones.Web.Mvc.UI.Components.Twitter
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.UI.Components.Twitter;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 08/10/2011 11:50 AM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.Twitter.TwitterProfile.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.Twitter.Profile))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.Twitter.ClientTemplates.profile.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="profile", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.Twitter.Profile))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "0.9.3.26911")]
    public class Profile : DowJones.Web.Mvc.UI.ViewComponentBase<ProfileModel>
    {
#line hidden

        public Profile()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_TwitterProfile";
            }
        }
        public override void ExecuteTemplate()
        {





WriteLiteral("\r\n");


   CssClass = "dj_TwitterProfile"; 

WriteLiteral("xten");


        }
    }
}
