//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Dash.Components.DashboardComponent.Dashboard.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Dash.Components.DashboardComponent.ClientTemplates.container.html", "text/html")]

namespace DowJones.Dash.Components.DashboardComponent
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 12/04/2012 07:54 PM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Dash.Components.DashboardComponent.Dashboard.js", DependsOn=new string[] {
            "jquery-counter"}, ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Dash.Components.DashboardComponent.DashboardComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Dash.Components.DashboardComponent.ClientTemplates.container.html", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="container", DeclaringType=typeof(DowJones.Dash.Components.DashboardComponent.DashboardComponent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.27108")]
    public class DashboardComponent : DowJones.Web.Mvc.UI.ViewComponentBase
    {
#line hidden

        public DashboardComponent()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_Dashboard";
            }
        }
        public override void ExecuteTemplate()
        {




   CssClass = "dj_dashboard"; 

WriteLiteral("\r\n");


        }
    }
}
