//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Dash.Components.PlatformStats.PlatformStats.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Dash.Components.PlatformStats.ClientTemplates.container.html", "text/html")]

namespace DowJones.Dash.Components.PlatformStats
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 09/13/2012 04:19 PM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Dash.Components.PlatformStats.PlatformStats.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Dash.Components.PlatformStats.PlatformStatsComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Dash.Components.PlatformStats.ClientTemplates.container.html", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="container", DeclaringType=typeof(DowJones.Dash.Components.PlatformStats.PlatformStatsComponent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.27108")]
    public class PlatformStatsComponent : DowJones.Web.Mvc.UI.ViewComponentBase<Models.PlatformStats.PlatformStatsModel>
    {
#line hidden

        public PlatformStatsComponent()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_PlatformStats";
            }
        }
        public override void ExecuteTemplate()
        {




WriteLiteral("\r\n");


   CssClass = "dj_PlatformStatsModel"; 

        }
    }
}
