//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DowJones.Web.Mvc.Diagnostics.ResponseGenerator
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 04/12/2011 02:24 PM
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "0.9.3.26911")]
    public class ResponseGeneratorView : DowJones.Web.Mvc.UI.ViewComponentBase<dynamic>
    {
#line hidden

        public ResponseGeneratorView()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return null;
            }
        }
        public override void ExecuteTemplate()
        {


   
    var title = "Dow Jones Error Diagnostics Page"; 


WriteLiteral("<head>\r\n    <title>");


      Write(title);

WriteLiteral("</title>\r\n</head>\r\n<body>\r\n    <h1>");


   Write(title);

WriteLiteral("</h1>\r\n\r\n    <form method=\"get\">\r\n\r\n        <p>\r\n            <label for=\"StatusCo" +
"de\">Status Code</label>\r\n            <input name=\"StatusCode\" type=\"text\" value=" +
"\"");


                                                   Write(Model.StatusCode);

WriteLiteral("\" />\r\n        </p>\r\n\r\n        <p>\r\n            <label for=\"timeToProcess\">Time to" +
" Process (wait)</label>\r\n            <input name=\"timeToProcess\" type=\"text\" val" +
"ue=\"");


                                                      Write(Model.TimeToProcess);

WriteLiteral("\" />\r\n        </p>\r\n\r\n        <p>\r\n            <label for=\"Body\">Body</label>\r\n  " +
"          <br/>\r\n            <textarea name=\"Body\">");


                             Write(Model.Body);

WriteLiteral("</textarea>\r\n        </p>\r\n\r\n        <p>\r\n            <button type=\"submit\">Make " +
"Request</button>\r\n        </p>\r\n\r\n    </form>\r\n</body>");


        }
    }
}
