//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Showcase.CanvasModules.Demo.Editor.DemoCanvasModuleEditor.js", "text/javascript")]

namespace DowJones.Web.Showcase.CanvasModules.Demo.Editor
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 03/07/2011 02:03 PM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Showcase.CanvasModules.Demo.Editor.DemoCanvasModuleEditor.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Showcase.CanvasModules.Demo.Editor.DemoCanvasModuleEditor))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "0.9.3.26911")]
    public class DemoCanvasModuleEditor : DowJones.Web.Mvc.UI.ViewComponentBase<DowJones.Web.Showcase.CanvasModules.Demo.Editor.DemoCanvasModuleEditorModel>
    {
#line hidden

        public DemoCanvasModuleEditor()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_DemoCanvasModuleEditor";
            }
        }
        public override void ExecuteTemplate()
        {




   CssClass = "dj_DemoCanvasModuleEditor"; 

WriteLiteral("\r\n");


        }
    }
}
