//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.RegionalMap.RegionalMap.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.RegionalMap.jquery.regionalmap.css", "text/css")]

namespace DowJones.Web.Mvc.UI.Components.RegionalMap
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Extensions;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 08/10/2011 11:46 AM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.RegionalMap.RegionalMap.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.RegionalMap.RegionalMap))]
    [DowJones.Web.StylesheetResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.RegionalMap.jquery.regionalmap.css", ResourceKind=DowJones.Web.ClientResourceKind.Stylesheet, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.RegionalMap.RegionalMap))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "0.9.3.26911")]
    public class RegionalMap : DowJones.Web.Mvc.UI.ViewComponentBase<DowJones.Web.Mvc.UI.Components.RegionalMap.RegionalMapModel>
    {
#line hidden

        public RegionalMap()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_RegionalMap";
            }
        }
        public override void ExecuteTemplate()
        {






  
    CssClass = "dj_RegionalMap";
    Html.DJ().ScriptRegistry().WithHighCharts();


        }
    }
}
