//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.DateHistogram.DateHistogram.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.DateHistogram.ClientTemplates.DateHistogramContent" +
    "s.htm", "text/html")]

namespace DowJones.Web.Mvc.UI.Components.DateHistogram
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 07/19/2012 03:36 PM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.DateHistogram.DateHistogram.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.DateHistogram.DateHistogramComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.DateHistogram.ClientTemplates.DateHistogramContent" +
        "s.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="datehistogramContents", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.DateHistogram.DateHistogramComponent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.22175")]
    public class DateHistogramComponent : DowJones.Web.Mvc.UI.ViewComponentBase<DateHistogramModel>
    {
#line hidden

        public DateHistogramComponent()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_DateHistogram";
            }
        }
        public override void ExecuteTemplate()
        {





       
    CssClass = "dj_DateHistogram dj_DateNavigator";
    Html.DJ().ScriptRegistry().WithServiceProxy();
    Html.DJ().ScriptRegistry().WithJQueryUIWidgets();
    Html.DJ().ScriptRegistry().WithPopupBalloon();
    Html.DJ().ScriptRegistry().WithHighCharts();
 


        }
    }
}
