//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Canvas.Modules.TopNews.TopNewsCanvasModule.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Canvas.Modules.TopNews.TopNewsCanvasModule.css", "text/css")]

namespace DowJones.Web.Mvc.UI.Canvas.Modules.TopNews
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    using DowJones.Extensions;
    using DowJones.Web.Mvc.UI.Components.PortalHeadlineList;
    using DowJones.Web.Mvc.UI.Components.Models;
    using DowJones.Web.Mvc.UI.Canvas;
    using CanvasModels = DowJones.Web.Mvc.UI.Canvas.Models;
    
    // Last Generated Timestamp: 06/02/2011 02:09 PM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Canvas.Modules.TopNews.TopNewsCanvasModule.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Canvas.Modules.TopNews.TopNewsCanvasModule))]
    [DowJones.Web.StylesheetResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Canvas.Modules.TopNews.TopNewsCanvasModule.css", ResourceKind=DowJones.Web.ClientResourceKind.Stylesheet, DeclaringType=typeof(DowJones.Web.Mvc.UI.Canvas.Modules.TopNews.TopNewsCanvasModule))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "0.0.0.30158")]
    public class TopNewsCanvasModule : AbstractCanvasModule<DowJones.Web.Mvc.UI.Canvas.Models.TopNewsModule>
    {
#line hidden

        public TopNewsCanvasModule()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_TopNewsCanvasModule";
            }
        }
        public override void ExecuteTemplate()
        {











   
    CssClass += " dj_topNewsCanvasModule curated-module";



DefineSection("EditArea", () => {

WriteLiteral("\r\n    ");



WriteLiteral("\r\n    ");


Write(CreateChildControl(Model.Editor,
        new Dictionary<string, object> { { "class", "dj_Editor" } }));

WriteLiteral("\r\n");


});

WriteLiteral("\r\n");


DefineSection("ContentArea", () => {

WriteLiteral("\r\n    <div class=\"module-row article-row clearfix\">\r\n        ");



WriteLiteral("\r\n");


         for (var j = 0; j < Model.NewsItemsPerPage; j++)
        { 

WriteLiteral(@"            <div class=""module-col one-third"">
                <div class=""module-col-wrap standard-padding"">
                    <div class=""article-group"">
                        <h3 class=""module-col-title article-group-title"">
                        </h3>
                        ");


                    Write(CreateChildControl<PortalHeadlineListControl>(new PortalHeadlineListModel()
                    {
                        MaxNumHeadlinesToShow = 5,
                        ShowPublicationDateTime = true,
                        ShowSource = true,
                        DisplayNoResultsToken = true,
                        ShowAuthor = (j == (Model.NewsItemsPerPage - 1)),
                        MultimediaMode = (j == 1)
                    }));

WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n");


        }

WriteLiteral("    </div>\r\n    <div class=\"module-row clearfix\">\r\n        ");



WriteLiteral("\r\n");


         for (var j = 0; j < Model.NewsItemsPerPage; j++)
        { 

WriteLiteral(@"            <div class=""module-col one-third"">
                <div class=""module-col-wrap standard-padding"">
                    <ul class=""dc_list view-all-btn"">
                        <li class=""dc_item""><a href=""javascript:void(0);"" class=""dashboard-control dc_btn dc_btn-1"">");


                                                                                                               Write(Html.DJ().Token("viewAll"));

WriteLiteral("</a>\r\n                        </li>\r\n                    </ul>\r\n                <" +
"/div>\r\n            </div>\r\n");


        }

WriteLiteral("    </div>\r\n");


});


        }
    }
}
