//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.StockKiosk.ClientTemplates.stockkiosk.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.StockKiosk.StockKiosk.js", "text/javascript")]

namespace DowJones.Web.Mvc.UI.Components.StockKiosk
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 06/29/2012 01:30 PM
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.StockKiosk.ClientTemplates.stockkiosk.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="stockkiosk", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.StockKiosk.StockKioskComponent))]
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.StockKiosk.StockKiosk.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.StockKiosk.StockKioskComponent), DependsOn=new string[] {
            "JSON"})]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.22175")]
    public class StockKioskComponent : DowJones.Web.Mvc.UI.ViewComponentBase<StockKioskModel>
    {
#line hidden

        public StockKioskComponent()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_StockKiosk";
            }
        }
        public override void ExecuteTemplate()
        {






   
    CssClass = "dj_StockKiosk";

    DJ.ScriptRegistry()
        .WithHighCharts()
        .WithServiceProxy()
        .WithJQueryTools(); 


WriteLiteral("\r\n");


        }
    }
}
