//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.Search.UI.Components.Builders.Module.ModuleSearchBuilder.js", "text/javascript")]

namespace DowJones.Web.Mvc.Search.UI.Components.Builders.Module
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.Mvc.Html;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 10/20/2011 05:02 PM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.Search.UI.Components.Builders.Module.ModuleSearchBuilder.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.Search.UI.Components.Builders.Module.ModuleSearchBuilderComponent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "0.0.0.30158")]
    public class ModuleSearchBuilderComponent : DowJones.Web.Mvc.UI.ViewComponentBase<DowJones.Web.Mvc.Search.UI.Components.Builders.Module.ModuleSearchBuilder>
    {
#line hidden

        public ModuleSearchBuilderComponent()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_ModuleSearchBuilder";
            }
        }
        public override void ExecuteTemplate()
        {

WriteLiteral("\r\n");





   CssClass = "dj_ModuleSearchBuilder"; 

WriteLiteral("\r\n\r\n");


Write(Html.Hidden("kind", "module"));

WriteLiteral("\r\n");


Write(Html.Hidden("PageId", Model.PageId));

WriteLiteral("\r\n");


Write(Html.Hidden("PageName", Model.PageName));

WriteLiteral("\r\n");


Write(Html.Hidden("ModuleId", Model.ModuleId));

WriteLiteral("\r\n");


Write(Html.Hidden("ModulePart", Model.ModulePart));

WriteLiteral("\r\n");


Write(Html.Hidden("ChartId", Model.ChartId));

WriteLiteral("\r\n");


Write(Html.Hidden("SearchContext", Model.SearchContext));

WriteLiteral("\r\n\r\n");


        }
    }
}
