//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.ArticleTranslator.ArticleTranslatorControl.js", "text/javascript")]

namespace DowJones.Web.Mvc.UI.Components.ArticleTranslator
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 08/10/2011 11:43 AM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.ArticleTranslator.ArticleTranslatorControl.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.ArticleTranslator.ArticleTranslatorControl))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "0.9.3.26911")]
    public class ArticleTranslatorControl : DowJones.Web.Mvc.UI.ViewComponentBase<ArticleTranslatorModel>
    {
#line hidden

        public ArticleTranslatorControl()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_ArticleTranslatorControl";
            }
        }
        public override void ExecuteTemplate()
        {

WriteLiteral("\r\n");





   CssClass = "dj_ArticleTranslatorControl"; 

WriteLiteral(@"
<div class=""dj_article_translator_icon"">
   <div id=""translateArticleDiv""  class=""dj_article_translator_translatemainlink"">
        <a tabindex=""0"" href=""javascript:void(0)"" id=""TranslatelinkId"">
            <span class=""dj_article_translator_button_span""> ");


                                                        Write(Model.Tokens.ArticleTranslatorTitle);

WriteLiteral(@"</span>
        </a>
        <div id=""translateLanguagesDiv"" class=""dj_article_translator_languagesDiv"" >
            <div class=""dj_article_translator_header"">
                <div class=""dj_article_translator_floatleft""><strong>Available Languages</strong></div>
                <div class=""dj_article_translator_floatright""><a href=""javascript:void(0)"" id=""translateClose""><strong>X</strong>&nbsp;<strong>Close</strong></a></div>
            </div>
            <ul class=""dj_article_translator_body"">
");


                 foreach (string slang in Model.GetSortedLanguages())
                {
                    string[] lang = slang.Split('|');
                    if (Model.SourceLanguage != lang[1])
                    {

WriteLiteral("                        <li role=\"menuitem\">\r\n                            <a clas" +
"s=\"dj_article_translator_langclicklink\" href=\"#\" rel=\"{accessionnumber:\'");


                                                                                                      Write(Model.AccessionNo);

WriteLiteral("\',sourcelanguage:\'");


                                                                                                                                          Write(Model.SourceLanguage);

WriteLiteral("\',targetlanguageCode:\'");


                                                                                                                                                                                     Write(lang[1]);

WriteLiteral("\',targetlanguage:\'");


                                                                                                                                                                                                               Write(lang[0]);

WriteLiteral("\'}\" tabindex=-1>\r\n                                ");


                           Write(lang[0]);

WriteLiteral("\r\n                            </a>\r\n                        </li>\r\n");


                    }
                }

WriteLiteral("            </ul>\r\n        </div>\r\n   </div>\r\n</div>\r\n");


        }
    }
}
