//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.TrendingNews.TrendingNews.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.TrendingNews.ClientTemplates.trendingnewstop5succe" +
    "ss.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.TrendingNews.ClientTemplates.trendingnewspercentag" +
    "esuccess.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.TrendingNews.ClientTemplates.nodata.htm", "text/html")]

namespace DowJones.Web.Mvc.UI.Components.TrendingNews
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 08/14/2012 02:26 PM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.TrendingNews.TrendingNews.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.TrendingNews.TrendingNews))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.TrendingNews.ClientTemplates.trendingnewstop5succe" +
        "ss.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="trendingnewstop5success", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.TrendingNews.TrendingNews))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.TrendingNews.ClientTemplates.trendingnewspercentag" +
        "esuccess.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="trendingnewspercentagesuccess", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.TrendingNews.TrendingNews))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.TrendingNews.ClientTemplates.nodata.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="nodata", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.TrendingNews.TrendingNews))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.27108")]
    public class TrendingNews : DowJones.Web.Mvc.UI.ViewComponentBase<DowJones.Web.Mvc.UI.Components.TrendingNews.TrendingNewsModel>
    {
#line hidden

        public TrendingNews()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_TrendingNews";
            }
        }
        public override void ExecuteTemplate()
        {






WriteLiteral("\r\n\r\n\r\n");


        }
    }
}
