//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Dash.Components.BrowserShare.BrowserShare.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Dash.Components.BrowserShare.ClientTemplates.container.html", "text/html")]

namespace DowJones.Dash.Components.BrowserShare
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 10/19/2012 02:20 PM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Dash.Components.BrowserShare.BrowserShare.js", DependsOn=new string[] {
            "highcharts"}, ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Dash.Components.BrowserShare.BrowserShareComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Dash.Components.BrowserShare.ClientTemplates.container.html", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="container", DeclaringType=typeof(DowJones.Dash.Components.BrowserShare.BrowserShareComponent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.27108")]
    public class BrowserShareComponent : DowJones.Web.Mvc.UI.ViewComponentBase<Models.BrowserShare.BrowserShareModel>
    {
#line hidden

        public BrowserShareComponent()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_BrowserShare";
            }
        }
        public override void ExecuteTemplate()
        {





   CssClass = "dj_BrowserShare"; 

WriteLiteral("\r\n");


        }
    }
}
