//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.TranslateArticle.TranslateArticle.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.TranslateArticle.js.jquery.ui.stars.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.TranslateArticle.js.jquery.uni-form.js", "text/javascript")]

namespace DowJones.Web.Mvc.UI.Components.TranslateArticle
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 06/27/2012 03:58 PM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.TranslateArticle.TranslateArticle.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.TranslateArticle.TranslateArticleComponent))]
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.TranslateArticle.js.jquery.ui.stars.js", DependsOn=new string[] {
            "jquery-ui-widgets"}, ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.TranslateArticle.TranslateArticleComponent))]
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.TranslateArticle.js.jquery.uni-form.js", DependsOn=new string[] {
            "jquery-ui-widgets"}, ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.TranslateArticle.TranslateArticleComponent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.22175")]
    public class TranslateArticleComponent : DowJones.Web.Mvc.UI.ViewComponentBase<TranslateArticleModel>
    {
#line hidden

        public TranslateArticleComponent()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_TranslateArticle";
            }
        }
        public override void ExecuteTemplate()
        {

WriteLiteral("\r\n");





WriteLiteral("\r\n");


   CssClass = "dj_TranslateArticle"; 

WriteLiteral("\r\n\r\n<div class=\"article\">\r\n    <table class=\"dj_translate_title\" border=\"0\" cellp" +
"adding=\"0\" cellspacing=\"0\">\r\n        <tr>\r\n            <td class=\"dj_translate_t" +
"itle_langcode\">");


                                               Write(Model.Tokens.Langcode);

WriteLiteral("\r\n            </td>\r\n            <td class=\"dj_translate_title_langtext\">");


                                               Write(Model.Tokens.LangText);

WriteLiteral(@"
            </td>
            <td class=""dj_translate_title_rating_td"">
                <div class=""dj_translate_title_rating"">
                    <div class=""multiField"" id=""starify"">
                        <label for=""vote1"" class=""blockLabel"">
                            <input  type=""radio"" name=""vote"" id=""vote1"" value=""");


                                                                          Write(Model.Tokens.TranslationVeryDifficult);

WriteLiteral("\"/>\r\n                        </label>\r\n                        <label for=\"vote2\"" +
" class=\"blockLabel\">\r\n                            <input  type=\"radio\" name=\"vot" +
"e\" id=\"vote2\" value=\"");


                                                                          Write(Model.Tokens.TranslationSomewhatDifficult);

WriteLiteral("\" />\r\n                        </label>\r\n                        <label for=\"vote3" +
"\" class=\"blockLabel\">\r\n                            <input  type=\"radio\" name=\"vo" +
"te\" id=\"vote3\" value=\"");


                                                                          Write(Model.Tokens.TranslationGeneralUnderstanding);

WriteLiteral("\" />\r\n                        </label>\r\n                        <label for=\"vote4" +
"\" class=\"blockLabel\">\r\n                            <input  type=\"radio\" name=\"vo" +
"te\" id=\"vote4\" value=\"");


                                                                          Write(Model.Tokens.TranslationSomewhatEasy);

WriteLiteral("\"  />\r\n                        </label>\r\n                        <label for=\"vote" +
"5\" class=\"blockLabel\">\r\n                            <input  type=\"radio\" name=\"v" +
"ote\" id=\"vote5\" value=\"");


                                                                          Write(Model.Tokens.TranslationVeryEasy);

WriteLiteral("\"  />\r\n                        </label>\r\n                    </div>\r\n            " +
"        <div id=\"dj_translate_ratestatus\">\r\n                        ");


                   Write(Model.Tokens.RateTranslationReadability);

WriteLiteral(" &nbsp; &nbsp;\r\n                    </div>\r\n                </div>\r\n            <" +
"/td>\r\n        </tr>\r\n    </table>\r\n    <div class=\"dj_translate_disclaimer\">\r\n  " +
"      <div class=\"dj_translate_disclaimer_text\" id=\"translateDisclaimer\">\r\n     " +
"       ");


       Write(Model.Tokens.ArticleTranslateDisclaimer);

WriteLiteral("\r\n            <a href=\"javascript:void(0)\" class=\"dj_translate_disclaimer_link\">");


                                                                         Write(Model.Tokens.ClickForFullDisclaimer);

WriteLiteral("</a>\r\n        </div>\r\n        <div class=\"dj_translate_disclaimer_text\" id=\"trans" +
"lateDisclaimerFull\" style=\"display: none\">\r\n            ");


       Write(Model.Tokens.ArticleTranslateDisclaimerFull);

WriteLiteral("\r\n        </div>\r\n        <br />\r\n        <br />\r\n        <div class=\"dj_translat" +
"e_disclaimer_translator\">\r\n            ");


       Write(Model.Tokens.TranslatedByPre);

WriteLiteral(" &nbsp;LanguageWeaver Inc.&nbsp;");


                                                                    Write(Model.Tokens.TranslatedByPost);

WriteLiteral("&nbsp;\r\n            ");


       Write(Model.ArticleObject.sourceName);

WriteLiteral("\r\n            &nbsp;");


             Write(Model.Tokens.TranslatedByPostPost);

WriteLiteral("&nbsp;&nbsp;[");


                                                            Write(Model.Tokens.FCPBeta);

WriteLiteral("]\r\n        </div>\r\n    </div>\r\n    <div id=\"originalContent\" style=\"display: none" +
"\">\r\n        <div>\r\n            <div id=\"hd\">\r\n                ");


           Write(Model.RenderArticleTitle());

WriteLiteral("\r\n            </div>\r\n             ");


        Write(Model.RenderRemainingArticleTitle());

WriteLiteral("\r\n              \r\n    </div>\r\n    <div id=\"translatedContent\">\r\n    </div>\r\n    <" +
"div id=\"translatingMessage\" class=\"dj_translate_translatingmsg\" style=\"display: " +
"none\">\r\n        <b>");


      Write(Model.Tokens.TranslationInProgress);

WriteLiteral("...</b>\r\n    </div>\r\n    <div id=\"translatingMessageLargeArticle\" class=\"dj_trans" +
"late_translatingmsg\" style=\"display: none\">");


                                                                                                  Write(Model.Tokens.LargeArticleTranslationMsg);

WriteLiteral("</div>\r\n    <div id=\"translateButtons\" class=\"dj_translate_buttons\" style=\"displa" +
"y: none\">\r\n        <a href=\"javascript:void(0)\" class=\"dj_translate_TranslateMor" +
"e\">");


                                                                   Write(Model.Tokens.TranslateMore);

WriteLiteral("\r\n            >></a>&nbsp;|&nbsp; <a href=\"javascript:void(0)\" class=\"dj_translat" +
"e_TranslateAll\">");


                                                                                          Write(Model.Tokens.TranslateAll);

WriteLiteral("\r\n                >></a>\r\n    </div>\r\n    <div class=\"dj_translate_copyright_rule" +
"r\">\r\n    </div>\r\n</div>\r\n<div style=\"display: none\">\r\n    <span id=\"InputFormat\"" +
">HTML</span> <span id=\"PP\">");


                                                Write(Model.ProductPrefix);

WriteLiteral("</span> <span id=\"WordCount\">");


                                                                                                 Write(Model.ArticleObject.wordCount);

WriteLiteral("\r\n    </span><span id=\"SourceName\">");


                            Write(Model.ArticleObject.sourceName);

WriteLiteral("</span> <span id=\"AccessionNo\">");


                                                                                          Write(Model.ArticleObject.accessionNo);

WriteLiteral("</span>\r\n</div>\r\n<script type=\"text/javascript\">\r\n    sourceLanguage =\'");


                Write(Model.SourceLanguage);

WriteLiteral("\'; \r\n    TargetLanguage =\'");


                Write(Model.TargetLanguage);

WriteLiteral("\'; \r\n    wordCount=");


         Write(Model.ArticleObject.wordCount);

WriteLiteral(";\r\n    sourceName=\'");


           Write(Model.ArticleObject.sourceName);

WriteLiteral("\';\r\n    accessionNo=\'");


            Write(Model.ArticleObject.accessionNo);

WriteLiteral("\';\r\n    sourceCode=\'");


           Write(Model.ArticleObject.sourceCode);

WriteLiteral("\'\r\n</script>\r\n");


        }
    }
}
