//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.Quote.ClientTemplates.Error.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.Quote.ClientTemplates.Success.htm", "text/html", PerformSubstitution=true)]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.Quote.ClientTemplates.NoData.htm", "text/html", PerformSubstitution=true)]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.Quote.Quote.js", "text/javascript")]

namespace DowJones.Web.Mvc.UI.Components.Quote
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 03/25/2011 12:20 PM
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.Quote.ClientTemplates.Error.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="error", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.Quote.QuoteControl))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.Quote.ClientTemplates.Success.htm", PerformSubstitution=true, ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="success", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.Quote.QuoteControl))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.Quote.ClientTemplates.NoData.htm", PerformSubstitution=true, ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="noData", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.Quote.QuoteControl))]
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.Quote.Quote.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.Quote.QuoteControl))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "0.9.3.26911")]
    public class QuoteControl : DowJones.Web.Mvc.UI.ViewComponentBase<DowJones.Web.Mvc.UI.Components.Models.QuoteModel>
    {
#line hidden

        public QuoteControl()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_Quote";
            }
        }
        public override void ExecuteTemplate()
        {







   
    CssClass = "dj_Quote";



        }
    }
}
