//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Canvas.Modules.RegionalMap.RegionalMapCanvasModule.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Canvas.Modules.RegionalMap.RegionalMapCanvasModule.css", "text/css")]

namespace DowJones.Web.Mvc.UI.Canvas.Modules.RegionalMap
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.UI.Canvas.Modules;
    using DowJones.Web.Mvc.Extensions;
    using DowJones.Extensions;
    using DowJones.Web.Mvc.UI.Components.RegionalMap;
    using DowJones.Web.Mvc.UI.Canvas;
    using DowJones.Web.Mvc.UI.Canvas.Modules.Syndication;
    using DowJones.Web.Mvc.UI.Components.Models;
    using CanvasModels = DowJones.Web.Mvc.UI.Canvas.Models;
    using DowJones.Web.Mvc.UI.Canvas.Properties;
    
    // Last Generated Timestamp: 05/23/2011 11:22 AM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Canvas.Modules.RegionalMap.RegionalMapCanvasModule.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Canvas.Modules.RegionalMap.RegionalMapCanvasModule))]
    [DowJones.Web.StylesheetResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Canvas.Modules.RegionalMap.RegionalMapCanvasModule.css", ResourceKind=DowJones.Web.ClientResourceKind.Stylesheet, DeclaringType=typeof(DowJones.Web.Mvc.UI.Canvas.Modules.RegionalMap.RegionalMapCanvasModule))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "0.0.0.30158")]
    public class RegionalMapCanvasModule : DowJones.Web.Mvc.UI.Canvas.AbstractCanvasModule<DowJones.Web.Mvc.UI.Canvas.Modules.RegionalMapModule>
    {
#line hidden

        public RegionalMapCanvasModule()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_RegionalMapCanvasModule";
            }
        }
        public override void ExecuteTemplate()
        {









WriteLiteral("\r\n");





WriteLiteral("\r\n");


   CssClass = CssClass + "  dj_RegionalMapCanvasModule curated-module"; 
    


WriteLiteral("\r\n");


DefineSection("OptionsArea", () => {

WriteLiteral("\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("ContentArea", () => {

WriteLiteral("\r\n    <div class=\"dj_RegionalMap-container\">\r\n        ");


    Write(CreateChildControl<RegionalMap>(new RegionalMapModel{Size= MapSize.Large,ShowTooltips=false,ShowTextLabels=true,}));

WriteLiteral("\r\n    </div>\r\n    <div class=\"no-results\" style=\"display:none;\">\r\n        ");


   Write(Html.DJ().Token("noResults"));

WriteLiteral("\r\n    </div>\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("EditArea", () => {

WriteLiteral("\r\n   ");



WriteLiteral("\r\n\r\n   ");


Write(CreateChildControl(Model.Editor, 
        new Dictionary<string, object> { { "class", "dj_Editor industry" } }));

WriteLiteral("\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("HeaderArea", () => {

WriteLiteral("\r\n    <div class=\"scope regionalmap-TimePeriod\">\r\n");


          
            Array arrTimeFrames = Enum.GetValues(typeof(RegionalMapTimeFrame));
            Array.Reverse(arrTimeFrames);
            foreach (RegionalMapTimeFrame timeFrame in arrTimeFrames)
            {

WriteLiteral("                <span class=\"dj_btn ");


                                Write(Model.TimeFrame == timeFrame ? "" : "no-bg");

WriteLiteral("\" days=\"");


                                                                                     Write(timeFrame);

WriteLiteral("\">");


                                                                                                 Write(Html.DJ().Token(Model.GetAssignedToken(timeFrame)));

WriteLiteral("</span>\r\n");


            }
        

WriteLiteral("    </div>\r\n");


});

WriteLiteral("\r\n\r\n\r\n");


DefineSection("InfoArea", () => {

WriteLiteral("\r\n    ");



WriteLiteral("\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("MessageArea", () => {

WriteLiteral("\r\n    ");



WriteLiteral("\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("LoadingArea", () => {

WriteLiteral("\r\n    ");



WriteLiteral("\r\n");


});

WriteLiteral("\r\n");


        }
    }
}
