//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.SocialButtons.SocialButtons.js", "text/javascript")]

namespace DowJones.Web.Mvc.UI.Components.SocialButtons
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using System.Text;
    using DowJones.Infrastructure;
    using DowJones.Extensions;
    using DowJones.Ajax.Article;
    using DowJones.Web.Mvc.UI.Components.Article;
    using System.Text.RegularExpressions;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 07/17/2012 04:12 PM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.SocialButtons.SocialButtons.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.SocialButtons.SocialButtonsComponent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.27108")]
    public class SocialButtonsComponent : DowJones.Web.Mvc.UI.ViewComponentBase<DowJones.Web.Mvc.UI.Components.SocialButtons.SocialButtonsModel>
    {
#line hidden

        public SocialButtonsComponent()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_SocialButtons";
            }
        }
        public override void ExecuteTemplate()
        {











  
    TagName = Model.TagName.IsNullOrEmpty() ? "ul" : Model.TagName;
    CssClass = Model.ClassName.IsNullOrEmpty() ? "actions" :  string.Concat("actions ", Model.ClassName);



        }
    }
}
