// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ServiceResources.cs" company="Dow Jones">
//   © 2010 Dow Jones, Inc. All rights reserved.
// </copyright>
// <summary>
//   The base .
// </summary>
// --------------------------------------------------------------------------------------------------------------------

using System.Globalization;

namespace EMG.widgets.ui.Modules.Compression
{
    /// <summary>
    /// The base .
    /// </summary>
    internal static class ServiceResources
    {
        /// <summary>
        /// The credi t_ string.
        /// </summary>
        internal const string CREDIT_STRING = "/* This file was compressed using MbCompression library. http://blog.mironabramson.com */ ";

        /// <summary>
        /// The web resource compression module_ invalid request.
        /// </summary>
        internal const string WEB_RESOURCE_COMPRESSION_MODULE_INVALID_REQUEST = "This is an invalid webresource request.";

        /// <summary>
        /// The web resource compression module_ assembly not found.
        /// </summary>
        internal const string WEB_RESOURCE_COMPRESSION_MODULE_ASSEMBLY_NOT_FOUND = "Assembly {0} not found.";

        /// <summary>
        /// The web resource compression module_ resource not found.
        /// </summary>
        internal const string WEB_RESOURCE_COMPRESSION_MODULE_RESOURCE_NOT_FOUND = "Resource {0} not found in assembly.";

        /// <summary>
        /// The web resource compression module_ reflection not allowd.
        /// </summary>
        internal const string WEB_RESOURCE_COMPRESSION_MODULE_REFLECTION_NOT_ALLOWD = "Your server does not allow using reflection from your code. (Method: System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters not allowed) Add the attribute 'reflectionAlloweded=\"false\"' to your web.config in the CompressorSettings section.";

        /// <summary>
        /// The web resource compression module_ machine key missing.
        /// </summary>
        internal const string WEB_RESOURCE_COMPRESSION_MODULE_MACHINE_KEY_MISSING = "Because your server does not support reflection or you set the attribute 'reflectionAlloweded=\"false\"', You must specify a non-autogenerated machine key in your web.config to compress Webresource.axd";

        /// <summary>
        /// The file_ file not found.
        /// </summary>
        internal const string FILE_FILE_NOT_FOUND = "/* The requested file '{0}' was not found */";

        /// <summary>
        /// The i caching storage_ not_ valid.
        /// </summary>
        internal const string CACHING_STORAGE_NOT_VALID = "Caching storage not valid. Must be one of the following: FileSystem or OutputCache";

        /// <summary>
        /// The compression not supported.
        /// </summary>
        internal const string COMPRESSION_NOT_SUPPORTED = "The current request not support any encoding";

        /// <summary>
        /// The get string.
        /// </summary>
        /// <param name="strString">The str string.</param>
        /// <returns>A resource string.</returns>
        internal static string GetString(string strString)
        {
            return strString;
        }

        /// <summary>
        /// The get string.
        /// </summary>
        /// <param name="strString">The str string.</param>
        /// <param name="param1">The param 1.</param>
        /// <returns>A resource string.</returns>
        internal static string GetString(string strString, string param1)
        {
            return string.Format(CultureInfo.InvariantCulture, strString, param1);
        }
    }
}
