//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.AlertEditor.ClientTemplates.main.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.AlertEditor.ClientTemplates.filters.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.AlertEditor.AlertEditor.js", "text/javascript")]

namespace DowJones.Web.Mvc.UI.Components.AlertEditor
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 07/18/2012 05:19 PM
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.AlertEditor.ClientTemplates.main.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="main", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.AlertEditor.AlertEditorComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.AlertEditor.ClientTemplates.filters.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="filters", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.AlertEditor.AlertEditorComponent))]
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.AlertEditor.AlertEditor.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.AlertEditor.AlertEditorComponent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.22175")]
    public class AlertEditorComponent : DowJones.Web.Mvc.UI.ViewComponentBase<AlertEditorModel>
    {
#line hidden

        public AlertEditorComponent()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_AlertEditor";
            }
        }
        public override void ExecuteTemplate()
        {






   CssClass = "dj_AlertEditor"; 

WriteLiteral("\r\n");


        }
    }
}
