//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Dash.Modules.PageLoadByRegionCanvasModule.PageLoadByRegionCanvasModule.j" +
    "s", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Dash.Modules.PageLoadByRegionCanvasModule.ClientTemplates.navPills.html", "text/html")]

namespace DowJones.Dash.Modules.PageLoadByRegionCanvasModule
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using Components.StatsMap;
    using Web.Mvc.Extensions;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 12/18/2012 11:20 AM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Dash.Modules.PageLoadByRegionCanvasModule.PageLoadByRegionCanvasModule.j" +
        "s", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Dash.Modules.PageLoadByRegionCanvasModule.PageLoadByRegionCanvasModule))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Dash.Modules.PageLoadByRegionCanvasModule.ClientTemplates.navPills.html", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="navPills", DeclaringType=typeof(DowJones.Dash.Modules.PageLoadByRegionCanvasModule.PageLoadByRegionCanvasModule))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.27108")]
    public class PageLoadByRegionCanvasModule : DowJones.Web.Mvc.UI.Canvas.AbstractCanvasModule<DowJones.Dash.Modules.PageLoadByRegionModuleModel>
    {
#line hidden

        public PageLoadByRegionCanvasModule()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_PageLoadByRegionCanvasModule";
            }
        }
        public override void ExecuteTemplate()
        {



WriteLiteral("\r\n");




WriteLiteral("\r\n");


DefineSection("ContentArea", () => {

WriteLiteral("\r\n    ");


Write(Html.DJ().RenderComponent<StatsMapComponent>(Model.StatsMap));

WriteLiteral("\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("EditArea", () => {

WriteLiteral("\r\n    ");



WriteLiteral("\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("HeaderArea", () => {

WriteLiteral("\r\n    ");



WriteLiteral("\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("OptionsArea", () => {

WriteLiteral("\r\n    ");



WriteLiteral("\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("InfoArea", () => {

WriteLiteral("\r\n    ");



WriteLiteral("\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("MessageArea", () => {

WriteLiteral("\r\n    ");



WriteLiteral("\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("LoadingArea", () => {

WriteLiteral("\r\n    ");



WriteLiteral("\r\n");


});


        }
    }
}
