//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.PostProcessing.ClientTemplates.modalDialog.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.PostProcessing.ClientTemplates.saveOptions.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.PostProcessing.ClientTemplates.formatOptions.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.PostProcessing.PostProcessing.js", "text/javascript")]

namespace DowJones.Web.Mvc.UI.Components.PostProcessing
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 01/18/2012 10:49 AM
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.PostProcessing.ClientTemplates.modalDialog.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="modalDialog", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.PostProcessing.PostProcessing))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.PostProcessing.ClientTemplates.saveOptions.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="saveOptions", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.PostProcessing.PostProcessing))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.PostProcessing.ClientTemplates.formatOptions.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="formatOptions", DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.PostProcessing.PostProcessing))]
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.PostProcessing.PostProcessing.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.PostProcessing.PostProcessing))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "0.0.0.30158")]
    public class PostProcessing : DowJones.Web.Mvc.UI.ViewComponentBase<DowJones.Web.Mvc.UI.Components.Models.PostProcessing>
    {
#line hidden

        public PostProcessing()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_PostProcessing";
            }
        }
        public override void ExecuteTemplate()
        {








   CssClass = "dj_PostProcessing"; 


 if (Model != null)
{
    if (Model.ShowActionsCheckBox)
    { 

WriteLiteral("    <div class=\"select dj_selectActions\">\r\n        <input type=\"checkbox\" name=\"s" +
"elect\" class=\"selectAll\" autocomplete=\"off\">\r\n");


         if (Model.EnableDuplicateOption)
        {

WriteLiteral("            <span class=\"dj_icon dj_icon-d-arrow-g\"></span>\r\n");



WriteLiteral("            <ul class=\"options hide dj_dupSelectOptions\">\r\n                <li cl" +
"ass=\"option\" data-selectdups=\"visible\">\r\n                    ");


               Write(Html.DJ().Token("selectArticlesVisible"));

WriteLiteral("\r\n                </li>\r\n                <li class=\"option\" data-selectdups=\"none" +
"\">\r\n                    ");


               Write(Html.DJ().Token("selectArticlesWithoutDuplicates"));

WriteLiteral("\r\n                </li>\r\n                <li class=\"option\" data-selectdups=\"all\"" +
">\r\n                    ");


               Write(Html.DJ().Token("selectArticlesWithDuplicates"));

WriteLiteral("\r\n                </li>\r\n            </ul>\r\n");


        }

WriteLiteral("    </div>\r\n");


    }

WriteLiteral("    <ul class=\"actions\">\r\n");


         foreach (var item in Model.PostProcessingOptions)
        {

WriteLiteral("            <li><span title=\"");


                        Write(Html.DJ().Token(item.ToString().ToLower() + "ArticlesTitle"));

WriteLiteral("\" \r\n                        class=\"dj_icon dj_icon-inactive-");


                                                   Write(item.ToString().ToLower());

WriteLiteral(" dj_icon-");


                                                                                      Write(item.ToString().ToLower());

WriteLiteral("\">\r\n            </span></li>\r\n");


        }

WriteLiteral("    </ul>\r\n");


}


        }
    }
}
