//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Prod.X.Components.Earnings.Earnings.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Prod.X.Components.Earnings.ClientTemplates.Error.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Prod.X.Components.Earnings.ClientTemplates.NoData.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Prod.X.Components.Earnings.ClientTemplates.Success-Small.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Prod.X.Components.Earnings.ClientTemplates.Success-Medium.htm", "text/html")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Prod.X.Components.Earnings.ClientTemplates.Success-Large.htm", "text/html")]

namespace DowJones.Prod.X.Components.Earnings
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 07/03/2013 04:26 PM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Prod.X.Components.Earnings.Earnings.js", DependsOn=new string[] {
            "bootstrap",
            "responseJs",
            "highchartsNew"}, ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Prod.X.Components.Earnings.EarningsViewComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Prod.X.Components.Earnings.ClientTemplates.Error.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="error", DeclaringType=typeof(DowJones.Prod.X.Components.Earnings.EarningsViewComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Prod.X.Components.Earnings.ClientTemplates.NoData.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="noData", DeclaringType=typeof(DowJones.Prod.X.Components.Earnings.EarningsViewComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Prod.X.Components.Earnings.ClientTemplates.Success-Small.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="successSmall", DeclaringType=typeof(DowJones.Prod.X.Components.Earnings.EarningsViewComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Prod.X.Components.Earnings.ClientTemplates.Success-Medium.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="successMedium", DeclaringType=typeof(DowJones.Prod.X.Components.Earnings.EarningsViewComponent))]
    [DowJones.Web.ClientTemplateResourceAttribute(null, ResourceName="DowJones.Prod.X.Components.Earnings.ClientTemplates.Success-Large.htm", ResourceKind=DowJones.Web.ClientResourceKind.ClientTemplate, TemplateId="successLarge", DeclaringType=typeof(DowJones.Prod.X.Components.Earnings.EarningsViewComponent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.27108")]
    public class EarningsViewComponent : DowJones.Web.Mvc.UI.ViewComponentBase<Models.Components.Earnings.EarningsComponentModel>
    {
#line hidden

        public EarningsViewComponent()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_Earnings";
            }
        }
        public override void ExecuteTemplate()
        {









   CssClass = "dj_Earnings"; 

WriteLiteral("\r\n");


        }
    }
}
