//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.NewsStandTicker.NewsStandTicker.js", "text/javascript")]
[assembly: System.Web.UI.WebResourceAttribute("DowJones.Web.Mvc.UI.Components.NewsStandTicker.jquery.SmoothScrollDiv.js", "text/javascript")]

namespace DowJones.Web.Mvc.UI.Components.NewsStandTicker
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using DowJones.Web.Mvc.Extensions;
    
    // Last Generated Timestamp: 06/29/2012 12:59 PM
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.NewsStandTicker.NewsStandTicker.js", ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.NewsStandTicker.NewsStandTickerComponent))]
    [DowJones.Web.ScriptResourceAttribute(null, ResourceName="DowJones.Web.Mvc.UI.Components.NewsStandTicker.jquery.SmoothScrollDiv.js", DependsOn=new string[] {
            "jquery-ui-widgets"}, ResourceKind=DowJones.Web.ClientResourceKind.Script, DeclaringType=typeof(DowJones.Web.Mvc.UI.Components.NewsStandTicker.NewsStandTickerComponent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorViewComponentClassGenerator", "1.0.0.22175")]
    public class NewsStandTickerComponent : DowJones.Web.Mvc.UI.ViewComponentBase<NewsStandTickerModel>
    {
#line hidden

        public NewsStandTickerComponent()
        {
        }
        public override string ClientPluginName
        {
            get
            {
                return "dj_NewsStandTicker";
            }
        }
        public override void ExecuteTemplate()
        {





  
    DJ.ScriptRegistry().WithJQueryUIWidgets();
 


        }
    }
}
